// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOperatingSystem() {
  return window['go']['main']['App']['GetOperatingSystem']();
}

export function OpenFileSelectionDialog(arg1) {
  return window['go']['main']['App']['OpenFileSelectionDialog'](arg1);
}
