// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['resources']['EndpointsService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['resources']['EndpointsService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['resources']['EndpointsService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['resources']['EndpointsService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['resources']['EndpointsService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['resources']['EndpointsService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['resources']['EndpointsService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['resources']['EndpointsService']['List'](arg1);
}

export function Lock() {
  return window['go']['resources']['EndpointsService']['Lock']();
}

export function RLock() {
  return window['go']['resources']['EndpointsService']['RLock']();
}

export function RLocker() {
  return window['go']['resources']['EndpointsService']['RLocker']();
}

export function RUnlock() {
  return window['go']['resources']['EndpointsService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['resources']['EndpointsService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['resources']['EndpointsService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['resources']['EndpointsService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['resources']['EndpointsService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['resources']['EndpointsService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['resources']['EndpointsService']['TryLock']();
}

export function TryRLock() {
  return window['go']['resources']['EndpointsService']['TryRLock']();
}

export function Unlock() {
  return window['go']['resources']['EndpointsService']['Unlock']();
}
