// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['resources']['NamespaceService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['resources']['NamespaceService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['resources']['NamespaceService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['resources']['NamespaceService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['resources']['NamespaceService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['resources']['NamespaceService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['resources']['NamespaceService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['resources']['NamespaceService']['List'](arg1);
}

export function Lock() {
  return window['go']['resources']['NamespaceService']['Lock']();
}

export function RLock() {
  return window['go']['resources']['NamespaceService']['RLock']();
}

export function RLocker() {
  return window['go']['resources']['NamespaceService']['RLocker']();
}

export function RUnlock() {
  return window['go']['resources']['NamespaceService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['resources']['NamespaceService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['resources']['NamespaceService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['resources']['NamespaceService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['resources']['NamespaceService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['resources']['NamespaceService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['resources']['NamespaceService']['TryLock']();
}

export function TryRLock() {
  return window['go']['resources']['NamespaceService']['TryRLock']();
}

export function Unlock() {
  return window['go']['resources']['NamespaceService']['Unlock']();
}
