// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['resources']['ServiceService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['resources']['ServiceService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['resources']['ServiceService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['resources']['ServiceService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['resources']['ServiceService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['resources']['ServiceService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['resources']['ServiceService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['resources']['ServiceService']['List'](arg1);
}

export function Lock() {
  return window['go']['resources']['ServiceService']['Lock']();
}

export function RLock() {
  return window['go']['resources']['ServiceService']['RLock']();
}

export function RLocker() {
  return window['go']['resources']['ServiceService']['RLocker']();
}

export function RUnlock() {
  return window['go']['resources']['ServiceService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['resources']['ServiceService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['resources']['ServiceService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['resources']['ServiceService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['resources']['ServiceService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['resources']['ServiceService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['resources']['ServiceService']['TryLock']();
}

export function TryRLock() {
  return window['go']['resources']['ServiceService']['TryRLock']();
}

export function Unlock() {
  return window['go']['resources']['ServiceService']['Unlock']();
}
