// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['resources']['ServiceAccountService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['resources']['ServiceAccountService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['resources']['ServiceAccountService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['resources']['ServiceAccountService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['resources']['ServiceAccountService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['resources']['ServiceAccountService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['resources']['ServiceAccountService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['resources']['ServiceAccountService']['List'](arg1);
}

export function Lock() {
  return window['go']['resources']['ServiceAccountService']['Lock']();
}

export function RLock() {
  return window['go']['resources']['ServiceAccountService']['RLock']();
}

export function RLocker() {
  return window['go']['resources']['ServiceAccountService']['RLocker']();
}

export function RUnlock() {
  return window['go']['resources']['ServiceAccountService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['resources']['ServiceAccountService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['resources']['ServiceAccountService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['resources']['ServiceAccountService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['resources']['ServiceAccountService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['resources']['ServiceAccountService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['resources']['ServiceAccountService']['TryLock']();
}

export function TryRLock() {
  return window['go']['resources']['ServiceAccountService']['TryRLock']();
}

export function Unlock() {
  return window['go']['resources']['ServiceAccountService']['Unlock']();
}
