// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategories() {
  return window['go']['settings']['provider']['GetCategories']();
}

export function GetCategory(arg1) {
  return window['go']['settings']['provider']['GetCategory'](arg1);
}

export function GetCategoryValues(arg1) {
  return window['go']['settings']['provider']['GetCategoryValues'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['settings']['provider']['GetSetting'](arg1);
}

export function GetSettingValue(arg1) {
  return window['go']['settings']['provider']['GetSettingValue'](arg1);
}

export function HasSetting(arg1) {
  return window['go']['settings']['provider']['HasSetting'](arg1);
}

export function Initialize(arg1, arg2) {
  return window['go']['settings']['provider']['Initialize'](arg1, arg2);
}

export function ListSettings() {
  return window['go']['settings']['provider']['ListSettings']();
}

export function LoadSettings() {
  return window['go']['settings']['provider']['LoadSettings']();
}

export function RegisterSetting(arg1, arg2) {
  return window['go']['settings']['provider']['RegisterSetting'](arg1, arg2);
}

export function RegisterSettings(arg1, arg2) {
  return window['go']['settings']['provider']['RegisterSettings'](arg1, arg2);
}

export function ResetSetting(arg1) {
  return window['go']['settings']['provider']['ResetSetting'](arg1);
}

export function SaveSettings() {
  return window['go']['settings']['provider']['SaveSettings']();
}

export function SetSetting(arg1, arg2) {
  return window['go']['settings']['provider']['SetSetting'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['settings']['provider']['SetSettings'](arg1);
}
