// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper exposes only frontend-safe methods of pkgsettings.Provider.
 * Excluded: RegisterChangeHandler, RegisterSetting, RegisterSettings
 * 
 * 	(internal-only methods).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../../plugin-sdk/settings/models.js";

export function GetBool(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(122243240, id);
}

/**
 * GetCategories returns all category metadata for the UI settings navigation.
 */
export function GetCategories(): $CancellablePromise<settings$0.Category[]> {
    return $Call.ByID(269082212).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCategory returns a single settings category by ID, including full metadata
 * (Label, Icon, Description) from the registered category definitions and live
 * setting values from the in-memory provider.
 */
export function GetCategory(id: string): $CancellablePromise<settings$0.Category> {
    return $Call.ByID(1421156656, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetCategoryValues returns a flat map of setting values for a single category.
 */
export function GetCategoryValues(id: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3143996982, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetFloat(id: string): $CancellablePromise<number> {
    return $Call.ByID(1695819138, id);
}

export function GetFloatSlice(id: string): $CancellablePromise<number[]> {
    return $Call.ByID(1827194808, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetInt(id: string): $CancellablePromise<number> {
    return $Call.ByID(72059321, id);
}

export function GetIntSlice(id: string): $CancellablePromise<number[]> {
    return $Call.ByID(62418781, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSetting(id: string): $CancellablePromise<settings$0.Setting> {
    return $Call.ByID(2222012564, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSettingValue(id: string): $CancellablePromise<any> {
    return $Call.ByID(2753368941, id);
}

export function GetString(id: string): $CancellablePromise<string> {
    return $Call.ByID(3825211425, id);
}

export function GetStringSlice(id: string): $CancellablePromise<string[]> {
    return $Call.ByID(2121298005, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListSettings(): $CancellablePromise<settings$0.Store> {
    return $Call.ByID(3038957305).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * LoadSettings is a no-op reload trigger for the frontend. With bbolt-backed
 * persistence, settings are always in memory — this exists so the frontend's
 * "reload" button still has a valid binding. It re-reads from the in-memory
 * store (which is already current).
 */
export function LoadSettings(): $CancellablePromise<void> {
    return $Call.ByID(3369612893);
}

export function SetSetting(id: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(252556992, id, value);
}

export function SetSettings(settingsMap: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1704369097, settingsMap);
}

/**
 * Values returns a flat map of all setting values keyed by "category.settingID".
 * This is a host-side convenience for the frontend — it was removed from the SDK
 * Provider interface (plugins don't need it) but the UI settings context uses it
 * to populate the full settings state.
 */
export function Values(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2936263106).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = settings$0.Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = settings$0.Setting.createFrom;
const $$createType6 = $Create.Array($Create.Any);
var $$createType7 = (function $$initCreateType7(...args: any[]): any {
    if ($$createType7 === $$initCreateType7) {
        $$createType7 = $$createType8;
    }
    return $$createType7(...args);
});
const $$createType8 = $Create.Map($Create.Any, $$createType0);
