// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function GetPluginComponents(arg1:ui.GetPluginComponentsInput):Promise<{[key: string]: Array<ui.ResourceComponent>}>;

export function GetResourceAreaComponent(arg1:ui.GetResourceAreaComponentInput):Promise<ui.ResourceComponent>;

export function GetResourceComponents(arg1:ui.GetResourceComponentsInput):Promise<Array<ui.ResourceComponent>>;
