// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';

export function GetDependencyTree(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<graph.DependencyTree>;

export function GetRelated(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:any):Promise<Array<graph.GraphEdge>>;

export function GetRelationshipChain(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<Array<any>>;
