// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDependencyTree(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['resource']['GraphService']['GetDependencyTree'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetRelated(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['resource']['GraphService']['GetRelated'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetRelationshipChain(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['resource']['GraphService']['GetRelationshipChain'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
