// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logs} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:logs.CreateSessionOptions):Promise<logs.LogSession>;

export function GetSession(arg1:string):Promise<logs.LogSession>;

export function GetSupportedResources(arg1:string):Promise<Array<logs.Handler>>;

export function ListSessions():Promise<Array<logs.LogSession>>;

export function PauseSession(arg1:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function UpdateSessionOptions(arg1:string,arg2:logs.LogSessionOptions):Promise<logs.LogSession>;
