// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1:string,arg2:Record<string, any>):Promise<void>;

export function Error(arg1:string,arg2:Record<string, any>):Promise<void>;

export function Info(arg1:string,arg2:Record<string, any>):Promise<void>;

export function Log(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function ReadLog(arg1:string):Promise<string>;

export function StartTail(arg1:string):Promise<void>;

export function StopTail(arg1:string):Promise<void>;

export function Warn(arg1:string,arg2:Record<string, any>):Promise<void>;
