// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper is an explicit delegation wrapper around settings.Controller.
 * Excluded: OnPluginInit, OnPluginStart, OnPluginStop, OnPluginShutdown,
 * 
 * 	OnPluginDestroy
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../../../../plugin-sdk/settings/models.js";

export function GetSetting(plugin: string, id: string): $CancellablePromise<settings$0.Setting> {
    return $Call.ByID(3867104420, plugin, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3795411887, pluginID);
}

export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(1053995964).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSettings(plugin: string): $CancellablePromise<{ [_ in string]?: settings$0.Setting }> {
    return $Call.ByID(3231741321, plugin).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PluginValues(plugin: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2597562645, plugin).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SetSetting(plugin: string, id: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(1481837168, plugin, id, value);
}

export function SetSettings(plugin: string, settingsMap: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(230212281, plugin, settingsMap);
}

export function Values(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2408440370).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = settings$0.Setting.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType0);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
