// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper is an explicit delegation wrapper around exec.Controller.
 * Excluded: OnPluginInit, OnPluginStart, OnPluginStop, OnPluginShutdown,
 * 
 * 	OnPluginDestroy
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as exec$0 from "../../../../../plugin-sdk/pkg/v1/exec/models.js";

export function AttachSession(sessionID: string): $CancellablePromise<[exec$0.Session | null, string]> {
    return $Call.ByID(93318075, sessionID).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $Create.ByteSlice($result[1]);
        return $result;
    });
}

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1353297556, sessionID);
}

export function CreateSession(plugin: string, connectionID: string, opts: exec$0.SessionOptions): $CancellablePromise<exec$0.Session | null> {
    return $Call.ByID(608251756, plugin, connectionID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateTerminal(opts: exec$0.SessionOptions): $CancellablePromise<exec$0.Session | null> {
    return $Call.ByID(4182196712, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DetachSession(sessionID: string): $CancellablePromise<exec$0.Session | null> {
    return $Call.ByID(3993344525, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetHandler(plugin: string, resource: string): $CancellablePromise<exec$0.Handler | null> {
    return $Call.ByID(1779192716, plugin, resource).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetHandlers(): $CancellablePromise<{ [_ in string]?: { [_ in string]?: exec$0.Handler } }> {
    return $Call.ByID(4033362541).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPluginHandlers(plugin: string): $CancellablePromise<{ [_ in string]?: exec$0.Handler }> {
    return $Call.ByID(2619212338, plugin).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSession(sessionID: string): $CancellablePromise<exec$0.Session | null> {
    return $Call.ByID(1371268636, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3881019319, pluginID);
}

export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(3006426324).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListSessions(): $CancellablePromise<(exec$0.Session | null)[]> {
    return $Call.ByID(265791345).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ResizeSession(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1492965384, sessionID, rows, cols);
}

export function WriteSession(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(486465741, sessionID, data);
}

// Private type creation functions
const $$createType0 = exec$0.Session.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = exec$0.Handler.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $$createType2);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($$createType1);
