// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePortForwardSession(arg1) {
  return window['go']['networker']['Client']['ClosePortForwardSession'](arg1);
}

export function FindPortForwardSessions(arg1, arg2, arg3) {
  return window['go']['networker']['Client']['FindPortForwardSessions'](arg1, arg2, arg3);
}

export function GetPortForwardSession(arg1) {
  return window['go']['networker']['Client']['GetPortForwardSession'](arg1);
}

export function GetSupportedPortForwardTargets(arg1) {
  return window['go']['networker']['Client']['GetSupportedPortForwardTargets'](arg1);
}

export function ListAllPortForwardSessions() {
  return window['go']['networker']['Client']['ListAllPortForwardSessions']();
}

export function ListPortForwardSessions(arg1, arg2) {
  return window['go']['networker']['Client']['ListPortForwardSessions'](arg1, arg2);
}

export function StartResourcePortForwardingSession(arg1, arg2, arg3) {
  return window['go']['networker']['Client']['StartResourcePortForwardingSession'](arg1, arg2, arg3);
}
