// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetSetting(arg1:string,arg2:string):Promise<settings.Setting>;

export function ListPlugins():Promise<Array<string>>;

export function ListSettings(arg1:string):Promise<Record<string, settings.Setting>>;

export function PluginValues(arg1:string):Promise<Record<string, any>>;

export function SetSetting(arg1:string,arg2:string,arg3:any):Promise<void>;

export function SetSettings(arg1:string,arg2:Record<string, any>):Promise<void>;

export function Values():Promise<Record<string, any>>;
