// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1:string,arg2:string):Promise<void>;

export function Get(arg1:string,arg2:string):Promise<any>;

export function Keys(arg1:string):Promise<Array<string>>;

export function Set(arg1:string,arg2:string,arg3:any):Promise<void>;
