// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';
import {services} from '../models';
import {sync} from '../models';
import {context} from '../models';

export function AddContext(arg1:string,arg2:string):Promise<void>;

export function AddResource(arg1:schema.GroupVersionResource):Promise<void>;

export function GetClusterContextPublisher():Promise<services.ClusterContextPublisher>;

export function GetClusterContextResourceStates(arg1:string):Promise<{[key: string]: boolean}>;

export function GetClusterContexts():Promise<{[key: string]: services.ClusterContext}>;

export function GetContext(arg1:string,arg2:string):Promise<services.ClusterContext>;

export function GetResources():Promise<{[key: string]: boolean}>;

export function ListContexts():Promise<{[key: string]: services.ClusterContext}>;

export function Lock():Promise<void>;

export function RLock():Promise<void>;

export function RLocker():Promise<sync.Locker>;

export function RUnlock():Promise<void>;

export function RemoveContext(arg1:string,arg2:string):Promise<void>;

export function RemoveResource(arg1:schema.GroupVersionResource):Promise<void>;

export function ResetAllResourcesReady():Promise<void>;

export function ResetResourceReady(arg1:schema.GroupVersionResource):Promise<void>;

export function Run(arg1:context.Context):Promise<void>;

export function SetClusterContextResourceError(arg1:string,arg2:string):Promise<void>;

export function SetClusterContextResourceNotReady(arg1:string,arg2:string):Promise<void>;

export function SetClusterContextResourceReady(arg1:string,arg2:string):Promise<void>;

export function SetResourceReady(arg1:schema.GroupVersionResource):Promise<void>;

export function StartContext(arg1:string):Promise<{[key: string]: boolean}>;

export function StopContext(arg1:string):Promise<void>;

export function SyncKubeconfig(arg1:string):Promise<void>;

export function TryLock():Promise<boolean>;

export function TryRLock():Promise<boolean>;

export function Unlock():Promise<void>;
