// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['List'](arg1);
}

export function Lock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Lock']();
}

export function RLock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['RLock']();
}

export function RLocker() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['RLocker']();
}

export function RUnlock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['rbacv1']['ClusterRoleBindingService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['TryLock']();
}

export function TryRLock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['TryRLock']();
}

export function Unlock() {
  return window['go']['rbacv1']['ClusterRoleBindingService']['Unlock']();
}
