// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['rbacv1']['RoleService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['rbacv1']['RoleService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['rbacv1']['RoleService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['rbacv1']['RoleService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['rbacv1']['RoleService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['rbacv1']['RoleService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['rbacv1']['RoleService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['rbacv1']['RoleService']['List'](arg1);
}

export function Lock() {
  return window['go']['rbacv1']['RoleService']['Lock']();
}

export function RLock() {
  return window['go']['rbacv1']['RoleService']['RLock']();
}

export function RLocker() {
  return window['go']['rbacv1']['RoleService']['RLocker']();
}

export function RUnlock() {
  return window['go']['rbacv1']['RoleService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['rbacv1']['RoleService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rbacv1']['RoleService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['rbacv1']['RoleService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['rbacv1']['RoleService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['rbacv1']['RoleService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['rbacv1']['RoleService']['TryLock']();
}

export function TryRLock() {
  return window['go']['rbacv1']['RoleService']['TryRLock']();
}

export function Unlock() {
  return window['go']['rbacv1']['RoleService']['Unlock']();
}
