// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['rbacv1']['RoleBindingService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['rbacv1']['RoleBindingService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['rbacv1']['RoleBindingService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['rbacv1']['RoleBindingService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['rbacv1']['RoleBindingService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['List'](arg1);
}

export function Lock() {
  return window['go']['rbacv1']['RoleBindingService']['Lock']();
}

export function RLock() {
  return window['go']['rbacv1']['RoleBindingService']['RLock']();
}

export function RLocker() {
  return window['go']['rbacv1']['RoleBindingService']['RLocker']();
}

export function RUnlock() {
  return window['go']['rbacv1']['RoleBindingService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['rbacv1']['RoleBindingService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['rbacv1']['RoleBindingService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['rbacv1']['RoleBindingService']['TryLock']();
}

export function TryRLock() {
  return window['go']['rbacv1']['RoleBindingService']['TryRLock']();
}

export function Unlock() {
  return window['go']['rbacv1']['RoleBindingService']['Unlock']();
}
