// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {trivy} from '../models';

export function Scan(arg1:trivy.Command,arg2:string,arg3:trivy.ScanOptions):Promise<trivy.ScanResult>;
