// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['pluginlog']['Manager']['Close']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['pluginlog']['Manager']['GetLogs'](arg1, arg2);
}

export function ListStreams() {
  return window['go']['pluginlog']['Manager']['ListStreams']();
}

export function LogDir() {
  return window['go']['pluginlog']['Manager']['LogDir']();
}

export function OnEmit(arg1) {
  return window['go']['pluginlog']['Manager']['OnEmit'](arg1);
}

export function SearchLogs(arg1, arg2) {
  return window['go']['pluginlog']['Manager']['SearchLogs'](arg1, arg2);
}

export function Stream(arg1) {
  return window['go']['pluginlog']['Manager']['Stream'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['pluginlog']['Manager']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['pluginlog']['Manager']['Unsubscribe'](arg1);
}
