// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * AggregateValue represents aggregated metric data over a window.
 */
export class AggregateValue {
    "metric_id": string;
    "min": number;
    "max": number;
    "avg": number;
    "sum": number;
    "p50": number;
    "p90": number;
    "p99": number;
    "count": number;
    "window": time$0.Duration;
    "labels": { [_ in string]?: string };

    /** Creates a new AggregateValue instance. */
    constructor($$source: Partial<AggregateValue> = {}) {
        if (!("metric_id" in $$source)) {
            this["metric_id"] = "";
        }
        if (!("min" in $$source)) {
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            this["max"] = 0;
        }
        if (!("avg" in $$source)) {
            this["avg"] = 0;
        }
        if (!("sum" in $$source)) {
            this["sum"] = 0;
        }
        if (!("p50" in $$source)) {
            this["p50"] = 0;
        }
        if (!("p90" in $$source)) {
            this["p90"] = 0;
        }
        if (!("p99" in $$source)) {
            this["p99"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("window" in $$source)) {
            this["window"] = time$0.Duration.$zero;
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AggregateValue instance from a string or object.
     */
    static createFrom($$source: any = {}): AggregateValue {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField10_0($$parsedSource["labels"]);
        }
        return new AggregateValue($$parsedSource as Partial<AggregateValue>);
    }
}

/**
 * ColorRange defines a color to use for a range of metric values.
 */
export class ColorRange {
    "min": number;
    "max": number;
    "color": string;

    /** Creates a new ColorRange instance. */
    constructor($$source: Partial<ColorRange> = {}) {
        if (!("min" in $$source)) {
            this["min"] = 0;
        }
        if (!("max" in $$source)) {
            this["max"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorRange instance from a string or object.
     */
    static createFrom($$source: any = {}): ColorRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorRange($$parsedSource as Partial<ColorRange>);
    }
}

/**
 * CurrentValue represents the current value of a metric.
 */
export class CurrentValue {
    "metric_id": string;
    "value": number;
    "timestamp": time$0.Time;
    "labels": { [_ in string]?: string };

    /** Creates a new CurrentValue instance. */
    constructor($$source: Partial<CurrentValue> = {}) {
        if (!("metric_id" in $$source)) {
            this["metric_id"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentValue instance from a string or object.
     */
    static createFrom($$source: any = {}): CurrentValue {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField3_0($$parsedSource["labels"]);
        }
        return new CurrentValue($$parsedSource as Partial<CurrentValue>);
    }
}

/**
 * DataPoint represents a single data point in a time series.
 */
export class DataPoint {
    "timestamp": time$0.Time;
    "value": number;
    "labels": { [_ in string]?: string };

    /** Creates a new DataPoint instance. */
    constructor($$source: Partial<DataPoint> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): DataPoint {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new DataPoint($$parsedSource as Partial<DataPoint>);
    }
}

/**
 * Handler maps a resource key to its available metrics.
 */
export class Handler {
    "resource": string;
    "metrics": MetricDescriptor[];

    /** Creates a new Handler instance. */
    constructor($$source: Partial<Handler> = {}) {
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Handler instance from a string or object.
     */
    static createFrom($$source: any = {}): Handler {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField1_0($$parsedSource["metrics"]);
        }
        return new Handler($$parsedSource as Partial<Handler>);
    }
}

/**
 * MetricDescriptor describes a single metric.
 */
export class MetricDescriptor {
    "id": string;
    "name": string;
    "unit": MetricUnit;
    "icon": string;
    "color_ranges": ColorRange[];
    "format_string": string;
    "supported_shapes": MetricShape[];
    "chart_group": string;

    /** Creates a new MetricDescriptor instance. */
    constructor($$source: Partial<MetricDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("unit" in $$source)) {
            this["unit"] = MetricUnit.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("color_ranges" in $$source)) {
            this["color_ranges"] = [];
        }
        if (!("format_string" in $$source)) {
            this["format_string"] = "";
        }
        if (!("supported_shapes" in $$source)) {
            this["supported_shapes"] = [];
        }
        if (!("chart_group" in $$source)) {
            this["chart_group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricDescriptor {
        const $$createField4_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color_ranges" in $$parsedSource) {
            $$parsedSource["color_ranges"] = $$createField4_0($$parsedSource["color_ranges"]);
        }
        if ("supported_shapes" in $$parsedSource) {
            $$parsedSource["supported_shapes"] = $$createField6_0($$parsedSource["supported_shapes"]);
        }
        return new MetricDescriptor($$parsedSource as Partial<MetricDescriptor>);
    }
}

/**
 * MetricResult wraps one of the possible metric result types.
 */
export class MetricResult {
    "time_series"?: TimeSeries | null;
    "current_value"?: CurrentValue | null;
    "aggregate_value"?: AggregateValue | null;

    /** Creates a new MetricResult instance. */
    constructor($$source: Partial<MetricResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetricResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MetricResult {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("time_series" in $$parsedSource) {
            $$parsedSource["time_series"] = $$createField0_0($$parsedSource["time_series"]);
        }
        if ("current_value" in $$parsedSource) {
            $$parsedSource["current_value"] = $$createField1_0($$parsedSource["current_value"]);
        }
        if ("aggregate_value" in $$parsedSource) {
            $$parsedSource["aggregate_value"] = $$createField2_0($$parsedSource["aggregate_value"]);
        }
        return new MetricResult($$parsedSource as Partial<MetricResult>);
    }
}

/**
 * MetricShape indicates the type of metric data.
 */
export enum MetricShape {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ShapeCurrent = 0,
    ShapeTimeseries = 1,
    ShapeAggregate = 2,
};

/**
 * MetricUnit represents the unit of a metric value.
 */
export enum MetricUnit {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    UnitNone = 0,
    UnitBytes = 1,
    UnitKB = 2,
    UnitMB = 3,
    UnitGB = 4,
    UnitPercentage = 5,
    UnitMillis = 6,
    UnitSeconds = 7,
    UnitCount = 8,
    UnitOpsPerSec = 9,
    UnitBytesPerSec = 10,
    UnitMillicores = 11,
    UnitCores = 12,
};

/**
 * QueryRequest is the Go-side representation of a metric query.
 */
export class QueryRequest {
    "resource_key": string;
    "resource_id": string;
    "resource_namespace": string;
    "resource_data": { [_ in string]?: any };
    "metric_ids": string[];
    "shape": MetricShape;
    "start_time": time$0.Time;
    "end_time": time$0.Time;
    "step": time$0.Duration;
    "params": { [_ in string]?: string };

    /** Creates a new QueryRequest instance. */
    constructor($$source: Partial<QueryRequest> = {}) {
        if (!("resource_key" in $$source)) {
            this["resource_key"] = "";
        }
        if (!("resource_id" in $$source)) {
            this["resource_id"] = "";
        }
        if (!("resource_namespace" in $$source)) {
            this["resource_namespace"] = "";
        }
        if (!("resource_data" in $$source)) {
            this["resource_data"] = {};
        }
        if (!("metric_ids" in $$source)) {
            this["metric_ids"] = [];
        }
        if (!("shape" in $$source)) {
            this["shape"] = MetricShape.$zero;
        }
        if (!("start_time" in $$source)) {
            this["start_time"] = null;
        }
        if (!("end_time" in $$source)) {
            this["end_time"] = null;
        }
        if (!("step" in $$source)) {
            this["step"] = time$0.Duration.$zero;
        }
        if (!("params" in $$source)) {
            this["params"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryRequest {
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resource_data" in $$parsedSource) {
            $$parsedSource["resource_data"] = $$createField3_0($$parsedSource["resource_data"]);
        }
        if ("metric_ids" in $$parsedSource) {
            $$parsedSource["metric_ids"] = $$createField4_0($$parsedSource["metric_ids"]);
        }
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        return new QueryRequest($$parsedSource as Partial<QueryRequest>);
    }
}

/**
 * QueryResponse is the Go-side representation of a metric query response.
 */
export class QueryResponse {
    "success": boolean;
    "results": MetricResult[];
    "error": string;

    /** Creates a new QueryResponse instance. */
    constructor($$source: Partial<QueryResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResponse {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new QueryResponse($$parsedSource as Partial<QueryResponse>);
    }
}

/**
 * TimeSeries represents a series of data points for a metric.
 */
export class TimeSeries {
    "metric_id": string;
    "data_points": DataPoint[];
    "labels": { [_ in string]?: string };

    /** Creates a new TimeSeries instance. */
    constructor($$source: Partial<TimeSeries> = {}) {
        if (!("metric_id" in $$source)) {
            this["metric_id"] = "";
        }
        if (!("data_points" in $$source)) {
            this["data_points"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeSeries instance from a string or object.
     */
    static createFrom($$source: any = {}): TimeSeries {
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data_points" in $$parsedSource) {
            $$parsedSource["data_points"] = $$createField1_0($$parsedSource["data_points"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new TimeSeries($$parsedSource as Partial<TimeSeries>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = MetricDescriptor.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ColorRange.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = TimeSeries.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = CurrentValue.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = AggregateValue.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Map($Create.Any, $Create.Any);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = MetricResult.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = DataPoint.createFrom;
const $$createType17 = $Create.Array($$createType16);
