// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['storagev1']['CSINodeService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['storagev1']['CSINodeService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['storagev1']['CSINodeService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['storagev1']['CSINodeService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['storagev1']['CSINodeService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['storagev1']['CSINodeService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['storagev1']['CSINodeService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['storagev1']['CSINodeService']['List'](arg1);
}

export function Lock() {
  return window['go']['storagev1']['CSINodeService']['Lock']();
}

export function RLock() {
  return window['go']['storagev1']['CSINodeService']['RLock']();
}

export function RLocker() {
  return window['go']['storagev1']['CSINodeService']['RLocker']();
}

export function RUnlock() {
  return window['go']['storagev1']['CSINodeService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['storagev1']['CSINodeService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['storagev1']['CSINodeService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['storagev1']['CSINodeService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['storagev1']['CSINodeService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['storagev1']['CSINodeService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['storagev1']['CSINodeService']['TryLock']();
}

export function TryRLock() {
  return window['go']['storagev1']['CSINodeService']['TryRLock']();
}

export function Unlock() {
  return window['go']['storagev1']['CSINodeService']['Unlock']();
}
