// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Manager manages per-plugin log streams with persistence, buffering,
 * and optional real-time emission. It is safe for concurrent use.
 * 
 * Emission is subscription-gated: the emit callback only fires for plugins
 * that have been explicitly subscribed via [Subscribe]. This prevents
 * unnecessary serialization and transport overhead on the Wails event bus
 * when no UI consumer is listening.
 * 
 * Wails-bindable methods: GetLogs, ListStreams, SearchLogs, Subscribe, Unsubscribe.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes all managed log streams, flushing any buffered data.
 * After Close, the Manager should not be used.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(776005653);
}

/**
 * GetLogs returns recent log entries for a plugin. If count <= 0, all
 * buffered entries are returned. Entries are in chronological order
 * (oldest first).
 * 
 * This method is designed to be Wails-bound for UI hydration.
 */
export function GetLogs(pluginID: string, count: number): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(571489490, pluginID, count).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListStreams returns the plugin IDs of all active log streams, sorted
 * alphabetically.
 * 
 * This method is designed to be Wails-bound for UI discovery.
 */
export function ListStreams(): $CancellablePromise<string[]> {
    return $Call.ByID(2080884156).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LogDir returns the directory where plugin log files are stored.
 */
export function LogDir(): $CancellablePromise<string> {
    return $Call.ByID(3239038078);
}

/**
 * OnEmit registers a callback invoked for every log entry across all
 * plugin streams. Only one callback is active at a time; subsequent calls
 * replace the previous one. Pass nil to disable emission.
 * 
 * This is the integration point for Wails event emission — the caller
 * wraps runtime.EventsEmit in the callback to keep this package free
 * of Wails dependencies.
 */
export function OnEmit(fn: $models.EmitFunc): $CancellablePromise<void> {
    return $Call.ByID(3482006781, fn);
}

/**
 * SearchLogs returns buffered log entries for a plugin whose message
 * matches the given regex pattern. Returns an error if the pattern is
 * invalid.
 * 
 * This method is designed to be Wails-bound for UI search.
 */
export function SearchLogs(pluginID: string, pattern: string): $CancellablePromise<$models.LogEntry[]> {
    return $Call.ByID(1307147796, pluginID, pattern).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Stream returns the PluginLogStream for the named plugin, creating it
 * on first call. The returned stream implements io.Writer for use as an
 * hclog Output target.
 */
export function Stream(pluginID: string): $CancellablePromise<$models.PluginLogStream | null> {
    return $Call.ByID(2430954319, pluginID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Subscribe registers interest in real-time log emission for a plugin.
 * The emit callback will only fire for plugins with at least one subscriber.
 * Multiple calls increment a reference count — each must be paired with
 * [Unsubscribe]. Returns the current subscriber count for the plugin.
 * 
 * This method is designed to be Wails-bound so the frontend can opt in
 * to real-time log streaming when the user opens a log viewer.
 */
export function Subscribe(pluginID: string): $CancellablePromise<number> {
    return $Call.ByID(3482847089, pluginID);
}

/**
 * Unsubscribe decrements the subscriber count for a plugin. When the count
 * reaches zero, real-time emission stops for that plugin. Returns the
 * remaining subscriber count (0 means no more emission).
 * 
 * This method is designed to be Wails-bound so the frontend can opt out
 * when the user closes the log viewer.
 */
export function Unsubscribe(pluginID: string): $CancellablePromise<number> {
    return $Call.ByID(953789992, pluginID);
}

// Private type creation functions
const $$createType0 = $models.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.PluginLogStream.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
