// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogEntry represents a single log line from a plugin process.
 * Field names and JSON tags intentionally match devserver.LogEntry
 * for frontend consistency.
 */
export class LogEntry {
    "timestamp": string;
    "pluginID": string;

    /**
     * "plugin" (from hclog) — extensible
     */
    "source": string;

    /**
     * "trace" | "debug" | "info" | "warn" | "error"
     */
    "level": string;
    "message": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("pluginID" in $$source)) {
            this["pluginID"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}
