// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {registry} from '../models';
import {config} from '../models';
import {context} from '../models';
import {plugin} from '../models';
import {devserver} from '../models';

export function GetPlugin(arg1:string):Promise<types.PluginInfo>;

export function GetPluginDownloadStats(arg1:string):Promise<registry.DownloadStats>;

export function GetPluginMeta(arg1:string):Promise<config.PluginMeta>;

export function GetPluginReadme(arg1:string):Promise<string>;

export function GetPluginReleaseHistory(arg1:string):Promise<Array<registry.VersionInfo>>;

export function GetPluginReviews(arg1:string,arg2:number):Promise<Array<registry.Review>>;

export function GetPluginVersions(arg1:string):Promise<Array<registry.VersionInfo>>;

export function HandlePluginCrash(arg1:string):Promise<void>;

export function Initialize(arg1:context.Context):Promise<void>;

export function InstallFromPathPrompt():Promise<config.PluginMeta>;

export function InstallInDevMode():Promise<config.PluginMeta>;

export function InstallPluginFromPath(arg1:string):Promise<config.PluginMeta>;

export function InstallPluginVersion(arg1:string,arg2:string):Promise<config.PluginMeta>;

export function ListAvailablePlugins():Promise<Array<registry.AvailablePlugin>>;

export function ListPluginMetas():Promise<Array<config.PluginMeta>>;

export function ListPlugins():Promise<Array<types.PluginInfo>>;

export function LoadPlugin(arg1:string,arg2:plugin.LoadPluginOptions):Promise<types.PluginInfo>;

export function ReloadPlugin(arg1:string):Promise<types.PluginInfo>;

export function Run(arg1:context.Context):Promise<void>;

export function SearchPlugins(arg1:string,arg2:string,arg3:string):Promise<Array<registry.AvailablePlugin>>;

export function SetDevServerChecker(arg1:plugin.DevServerChecker):Promise<void>;

export function SetDevServerManager(arg1:devserver.DevServerManager):Promise<void>;

export function Shutdown():Promise<void>;

export function UninstallPlugin(arg1:string):Promise<types.PluginInfo>;

export function UnloadPlugin(arg1:string):Promise<void>;
