// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlugin(arg1) {
  return window['go']['plugin']['pluginManager']['GetPlugin'](arg1);
}

export function GetPluginDownloadStats(arg1) {
  return window['go']['plugin']['pluginManager']['GetPluginDownloadStats'](arg1);
}

export function GetPluginMeta(arg1) {
  return window['go']['plugin']['pluginManager']['GetPluginMeta'](arg1);
}

export function GetPluginReadme(arg1) {
  return window['go']['plugin']['pluginManager']['GetPluginReadme'](arg1);
}

export function GetPluginReleaseHistory(arg1) {
  return window['go']['plugin']['pluginManager']['GetPluginReleaseHistory'](arg1);
}

export function GetPluginReviews(arg1, arg2) {
  return window['go']['plugin']['pluginManager']['GetPluginReviews'](arg1, arg2);
}

export function GetPluginVersions(arg1) {
  return window['go']['plugin']['pluginManager']['GetPluginVersions'](arg1);
}

export function HandlePluginCrash(arg1) {
  return window['go']['plugin']['pluginManager']['HandlePluginCrash'](arg1);
}

export function Initialize(arg1) {
  return window['go']['plugin']['pluginManager']['Initialize'](arg1);
}

export function InstallFromPathPrompt() {
  return window['go']['plugin']['pluginManager']['InstallFromPathPrompt']();
}

export function InstallInDevMode() {
  return window['go']['plugin']['pluginManager']['InstallInDevMode']();
}

export function InstallPluginFromPath(arg1) {
  return window['go']['plugin']['pluginManager']['InstallPluginFromPath'](arg1);
}

export function InstallPluginVersion(arg1, arg2) {
  return window['go']['plugin']['pluginManager']['InstallPluginVersion'](arg1, arg2);
}

export function ListAvailablePlugins() {
  return window['go']['plugin']['pluginManager']['ListAvailablePlugins']();
}

export function ListPluginMetas() {
  return window['go']['plugin']['pluginManager']['ListPluginMetas']();
}

export function ListPlugins() {
  return window['go']['plugin']['pluginManager']['ListPlugins']();
}

export function LoadPlugin(arg1, arg2) {
  return window['go']['plugin']['pluginManager']['LoadPlugin'](arg1, arg2);
}

export function ReloadPlugin(arg1) {
  return window['go']['plugin']['pluginManager']['ReloadPlugin'](arg1);
}

export function Run(arg1) {
  return window['go']['plugin']['pluginManager']['Run'](arg1);
}

export function SearchPlugins(arg1, arg2, arg3) {
  return window['go']['plugin']['pluginManager']['SearchPlugins'](arg1, arg2, arg3);
}

export function SetDevServerChecker(arg1) {
  return window['go']['plugin']['pluginManager']['SetDevServerChecker'](arg1);
}

export function SetDevServerManager(arg1) {
  return window['go']['plugin']['pluginManager']['SetDevServerManager'](arg1);
}

export function Shutdown() {
  return window['go']['plugin']['pluginManager']['Shutdown']();
}

export function UninstallPlugin(arg1) {
  return window['go']['plugin']['pluginManager']['UninstallPlugin'](arg1);
}

export function UnloadPlugin(arg1) {
  return window['go']['plugin']['pluginManager']['UnloadPlugin'](arg1);
}
