// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['resource']['Client']['AddConnection'](arg1, arg2);
}

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Create'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Delete'](arg1, arg2, arg3, arg4);
}

export function Find(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Find'](arg1, arg2, arg3, arg4);
}

export function Get(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Get'](arg1, arg2, arg3, arg4);
}

export function GetConnection(arg1, arg2) {
  return window['go']['resource']['Client']['GetConnection'](arg1, arg2);
}

export function GetDefaultLayout(arg1) {
  return window['go']['resource']['Client']['GetDefaultLayout'](arg1);
}

export function GetLayout(arg1, arg2) {
  return window['go']['resource']['Client']['GetLayout'](arg1, arg2);
}

export function GetResourceDefinition(arg1, arg2) {
  return window['go']['resource']['Client']['GetResourceDefinition'](arg1, arg2);
}

export function GetResourceGroup(arg1, arg2) {
  return window['go']['resource']['Client']['GetResourceGroup'](arg1, arg2);
}

export function GetResourceGroups(arg1, arg2) {
  return window['go']['resource']['Client']['GetResourceGroups'](arg1, arg2);
}

export function GetResourceType(arg1, arg2) {
  return window['go']['resource']['Client']['GetResourceType'](arg1, arg2);
}

export function GetResourceTypes(arg1, arg2) {
  return window['go']['resource']['Client']['GetResourceTypes'](arg1, arg2);
}

export function HasResourceType(arg1, arg2) {
  return window['go']['resource']['Client']['HasResourceType'](arg1, arg2);
}

export function List(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['List'](arg1, arg2, arg3, arg4);
}

export function ListConnections(arg1) {
  return window['go']['resource']['Client']['ListConnections'](arg1);
}

export function ListPlugins() {
  return window['go']['resource']['Client']['ListPlugins']();
}

export function LoadConnections(arg1) {
  return window['go']['resource']['Client']['LoadConnections'](arg1);
}

export function RemoveConnection(arg1, arg2) {
  return window['go']['resource']['Client']['RemoveConnection'](arg1, arg2);
}

export function SetLayout(arg1, arg2, arg3) {
  return window['go']['resource']['Client']['SetLayout'](arg1, arg2, arg3);
}

export function StartConnection(arg1, arg2) {
  return window['go']['resource']['Client']['StartConnection'](arg1, arg2);
}

export function StartConnectionInformer(arg1, arg2) {
  return window['go']['resource']['Client']['StartConnectionInformer'](arg1, arg2);
}

export function StopConnection(arg1, arg2) {
  return window['go']['resource']['Client']['StopConnection'](arg1, arg2);
}

export function StopConnectionInformer(arg1, arg2) {
  return window['go']['resource']['Client']['StopConnectionInformer'](arg1, arg2);
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Update'](arg1, arg2, arg3, arg4);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['resource']['Client']['UpdateConnection'](arg1, arg2);
}
