// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['resource']['Client']['AddConnection'](arg1, arg2);
}

export function Create(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Create'](arg1, arg2, arg3, arg4);
}

export function Delete(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Delete'](arg1, arg2, arg3, arg4);
}

export function Find(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Find'](arg1, arg2, arg3, arg4);
}

export function Get(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Get'](arg1, arg2, arg3, arg4);
}

export function List(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['List'](arg1, arg2, arg3, arg4);
}

export function ListConnections(arg1) {
  return window['go']['resource']['Client']['ListConnections'](arg1);
}

export function RemoveConnection(arg1, arg2) {
  return window['go']['resource']['Client']['RemoveConnection'](arg1, arg2);
}

export function StartConnectionInformer(arg1, arg2) {
  return window['go']['resource']['Client']['StartConnectionInformer'](arg1, arg2);
}

export function StopConnectionInformer(arg1, arg2) {
  return window['go']['resource']['Client']['StopConnectionInformer'](arg1, arg2);
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['resource']['Client']['Update'](arg1, arg2, arg3, arg4);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['resource']['Client']['UpdateConnection'](arg1, arg2);
}
