// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['batchv1']['CronJobService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['batchv1']['CronJobService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['batchv1']['CronJobService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['batchv1']['CronJobService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['batchv1']['CronJobService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['batchv1']['CronJobService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['batchv1']['CronJobService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['batchv1']['CronJobService']['List'](arg1);
}

export function Lock() {
  return window['go']['batchv1']['CronJobService']['Lock']();
}

export function RLock() {
  return window['go']['batchv1']['CronJobService']['RLock']();
}

export function RLocker() {
  return window['go']['batchv1']['CronJobService']['RLocker']();
}

export function RUnlock() {
  return window['go']['batchv1']['CronJobService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['batchv1']['CronJobService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['batchv1']['CronJobService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['batchv1']['CronJobService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['batchv1']['CronJobService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['batchv1']['CronJobService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['batchv1']['CronJobService']['TryLock']();
}

export function TryRLock() {
  return window['go']['batchv1']['CronJobService']['TryRLock']();
}

export function Unlock() {
  return window['go']['batchv1']['CronJobService']['Unlock']();
}
