// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['batchv1']['JobService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['batchv1']['JobService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['batchv1']['JobService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['batchv1']['JobService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['batchv1']['JobService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['batchv1']['JobService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['batchv1']['JobService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['batchv1']['JobService']['List'](arg1);
}

export function Lock() {
  return window['go']['batchv1']['JobService']['Lock']();
}

export function RLock() {
  return window['go']['batchv1']['JobService']['RLock']();
}

export function RLocker() {
  return window['go']['batchv1']['JobService']['RLocker']();
}

export function RUnlock() {
  return window['go']['batchv1']['JobService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['batchv1']['JobService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['batchv1']['JobService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['batchv1']['JobService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['batchv1']['JobService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['batchv1']['JobService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['batchv1']['JobService']['TryLock']();
}

export function TryRLock() {
  return window['go']['batchv1']['JobService']['TryRLock']();
}

export function Unlock() {
  return window['go']['batchv1']['JobService']['Unlock']();
}
