// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper is an explicit delegation wrapper around networker.Controller.
 * Excluded: OnPluginInit, OnPluginStart, OnPluginStop, OnPluginShutdown,
 * 
 * 	OnPluginDestroy
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networker$0 from "../../../../../plugin-sdk/pkg/v1/networker/models.js";

export function ClosePortForwardSession(sessionID: string): $CancellablePromise<networker$0.PortForwardSession | null> {
    return $Call.ByID(182596922, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FindPortForwardSessions(pluginID: string, connectionID: string, request: networker$0.FindPortForwardSessionRequest): $CancellablePromise<(networker$0.PortForwardSession | null)[]> {
    return $Call.ByID(981100722, pluginID, connectionID, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPortForwardSession(sessionID: string): $CancellablePromise<networker$0.PortForwardSession | null> {
    return $Call.ByID(2157304970, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSupportedPortForwardTargets(pluginID: string): $CancellablePromise<string[]> {
    return $Call.ByID(650882, pluginID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3624690437, pluginID);
}

export function ListAllPortForwardSessions(): $CancellablePromise<(networker$0.PortForwardSession | null)[]> {
    return $Call.ByID(2195697754).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(167463150).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListPortForwardSessions(pluginID: string, connectionID: string): $CancellablePromise<(networker$0.PortForwardSession | null)[]> {
    return $Call.ByID(2090415403, pluginID, connectionID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartResourcePortForwardingSession(pluginID: string, connectionID: string, opts: networker$0.PortForwardSessionOptions): $CancellablePromise<networker$0.PortForwardSession | null> {
    return $Call.ByID(780445954, pluginID, connectionID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = networker$0.PortForwardSession.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
