// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as plugin$0 from "../../../../omniviewdev/omniview/backend/pkg/plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as devserver$0 from "../../../../omniviewdev/omniview/backend/pkg/plugin/devserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as networker$0 from "../../../../omniviewdev/plugin-sdk/pkg/v1/networker/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "core/networker/portforward/closed": networker$0.PortForwardSession | null;
            "core/networker/portforward/created": networker$0.PortForwardSession | null;
            "plugin/crash_recovery_failed": void;
            "plugin/deprecated_protocol": plugin$0.DeprecatedProtocolPayload;
            "plugin/dev_install_complete": void;
            "plugin/dev_install_error": void;
            "plugin/dev_install_start": void;
            "plugin/dev_reload_complete": void;
            "plugin/dev_reload_error": void;
            "plugin/dev_reload_start": void;
            "plugin/devserver/error": devserver$0.DevServerErrorPayload;
            "plugin/devserver/log": devserver$0.LogEntry[];
            "plugin/devserver/status": devserver$0.DevServerState;
            "plugin/init_complete": void;
            "plugin/install_error": void;
            "plugin/install_finished": void;
            "plugin/install_started": void;
            "plugin/recovered": void;
            "plugin/state_change": plugin$0.StateChangePayload;
            "plugin/state_write_error": void;
            "plugin/update_complete": void;
            "plugin/update_error": void;
            "plugin/update_started": void;
        }
    }
}
