// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TelemetryBinding exposes telemetry operations to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IngestFrontendSignals accepts a JSON payload from the frontend containing
 * logs, errors, and measurements, and converts them into backend telemetry
 * signals (Zap logs, OTel trace span events).
 */
export function IngestFrontendSignals(payload: string): $CancellablePromise<void> {
    return $Call.ByID(623015471, payload);
}
