// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Category is a group of settings. This is used to group settings together in the UI.
 */
export class Category {
    "settings": { [_ in string]?: Setting };
    "id": string;
    "label": string;
    "description": string;
    "icon": string;

    /** Creates a new Category instance. */
    constructor($$source: Partial<Category> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     */
    static createFrom($$source: any = {}): Category {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        return new Category($$parsedSource as Partial<Category>);
    }
}

export class Setting {
    /**
     * ID is the unique identifier of the setting
     */
    "id": string;

    /**
     * Label is the human readable label of the setting
     */
    "label": string;

    /**
     * Description is the human readable description of the setting
     */
    "description": string;

    /**
     * Type is the type of the setting
     */
    "type": SettingType;

    /**
     * Value is the value of the setting
     */
    "value": any;

    /**
     * Default is the default value of the setting
     */
    "default": any;

    /**
     * Options is an optional list of options for a select setting
     */
    "options": SettingOption[];

    /**
     * FileSelection is an optional setting for file selection
     */
    "fileSelection": SettingFileSelection | null;

    /**
     * Sensitive is a flag to indicate if the setting is sensitive and should not be
     * shown in the UI, nor allowed to be used by any other plugin.
     */
    "sensitive": boolean;

    /**
     * DevOnly indicates the setting should only be visible when dev mode is active.
     */
    "devOnly": boolean;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = SettingType.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }
        if (!("default" in $$source)) {
            this["default"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("fileSelection" in $$source)) {
            this["fileSelection"] = null;
        }
        if (!("sensitive" in $$source)) {
            this["sensitive"] = false;
        }
        if (!("devOnly" in $$source)) {
            this["devOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        if ("fileSelection" in $$parsedSource) {
            $$parsedSource["fileSelection"] = $$createField7_0($$parsedSource["fileSelection"]);
        }
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

export class SettingFileSelection {
    /**
     * Whether file selection should be allowed.
     */
    "enabled": boolean;

    /**
     * Allow the selection of folders.
     */
    "allowFolders": boolean;

    /**
     * The allowed extensions that should be selectable.
     */
    "extensions": string[];

    /**
     * Multiple files can be selected.
     */
    "multiple": boolean;

    /**
     * Whether the file selection should be saved as a relative path.
     */
    "relative": boolean;

    /**
     * DefaultPath is the default path for the file selection.
     */
    "defaultPath": string;

    /** Creates a new SettingFileSelection instance. */
    constructor($$source: Partial<SettingFileSelection> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("allowFolders" in $$source)) {
            this["allowFolders"] = false;
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("multiple" in $$source)) {
            this["multiple"] = false;
        }
        if (!("relative" in $$source)) {
            this["relative"] = false;
        }
        if (!("defaultPath" in $$source)) {
            this["defaultPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingFileSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingFileSelection {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        return new SettingFileSelection($$parsedSource as Partial<SettingFileSelection>);
    }
}

export class SettingOption {
    /**
     * Label is the human readable label of the option
     */
    "label": string;

    /**
     * Description is an optional human readable description of the option
     */
    "description": string;

    /**
     * Value is the value of the option
     */
    "value": any;

    /** Creates a new SettingOption instance. */
    constructor($$source: Partial<SettingOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingOption($$parsedSource as Partial<SettingOption>);
    }
}

export enum SettingType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Text is the type for a text field entry.
     */
    Text = "text",

    /**
     * Select is the type for a single-select field entry.
     */
    Select = "select",

    /**
     * MultiSelect is the type for a multi-select field entry.
     */
    MultiSelect = "multiselect",

    /**
     * Integer is the type for an integer field entry.
     */
    Integer = "integer",

    /**
     * Float is the type for a float field entry.
     */
    Float = "float",

    /**
     * Toggle is the type for a toggle field entry.
     */
    Toggle = "toggle",

    /**
     * Color is the type for a color field entry.
     */
    Color = "color",

    /**
     * DateTime is the type for a date time field entry.
     */
    DateTime = "datetime",

    /**
     * SettingTypePassword is the type for a password field entry.
     */
    Password = "password",
};

/**
 * The settings store is a map of maps. The first map is the category of the settings, and the second
 * map is the settings themselves. The key of the first map is the category name, and the key of the
 * second map is the setting ID.
 */
export type Store = { [_ in string]?: Category };

// Private type creation functions
const $$createType0 = Setting.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = SettingOption.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SettingFileSelection.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
