// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClusterContext(arg1) {
  return window['go']['appsv1']['DaemonSetService']['AddClusterContext'](arg1);
}

export function ClearEvents() {
  return window['go']['appsv1']['DaemonSetService']['ClearEvents']();
}

export function Delete(arg1, arg2) {
  return window['go']['appsv1']['DaemonSetService']['Delete'](arg1, arg2);
}

export function DispatchEvents() {
  return window['go']['appsv1']['DaemonSetService']['DispatchEvents']();
}

export function Edit(arg1, arg2, arg3) {
  return window['go']['appsv1']['DaemonSetService']['Edit'](arg1, arg2, arg3);
}

export function Get(arg1) {
  return window['go']['appsv1']['DaemonSetService']['Get'](arg1);
}

export function GroupVersionResource() {
  return window['go']['appsv1']['DaemonSetService']['GroupVersionResource']();
}

export function List(arg1) {
  return window['go']['appsv1']['DaemonSetService']['List'](arg1);
}

export function Lock() {
  return window['go']['appsv1']['DaemonSetService']['Lock']();
}

export function RLock() {
  return window['go']['appsv1']['DaemonSetService']['RLock']();
}

export function RLocker() {
  return window['go']['appsv1']['DaemonSetService']['RLocker']();
}

export function RUnlock() {
  return window['go']['appsv1']['DaemonSetService']['RUnlock']();
}

export function Run(arg1) {
  return window['go']['appsv1']['DaemonSetService']['Run'](arg1);
}

export function SetContext(arg1) {
  return window['go']['appsv1']['DaemonSetService']['SetContext'](arg1);
}

export function StartClusterContext(arg1) {
  return window['go']['appsv1']['DaemonSetService']['StartClusterContext'](arg1);
}

export function Stop() {
  return window['go']['appsv1']['DaemonSetService']['Stop']();
}

export function StopClusterContext(arg1) {
  return window['go']['appsv1']['DaemonSetService']['StopClusterContext'](arg1);
}

export function TryLock() {
  return window['go']['appsv1']['DaemonSetService']['TryLock']();
}

export function TryRLock() {
  return window['go']['appsv1']['DaemonSetService']['TryRLock']();
}

export function Unlock() {
  return window['go']['appsv1']['DaemonSetService']['Unlock']();
}
