// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper exposes only the frontend-safe methods of plugin.Manager.
 * Internal methods (SetDevServerChecker, SetPluginLogManager, HandlePluginCrash,
 * Initialize, Run, Shutdown) are excluded to avoid binding warnings from
 * interface/function-type parameters.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as registry$0 from "./registry/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../../plugin-sdk/pkg/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../../plugin-sdk/pkg/types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(3150413499, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPluginDownloadStats(pluginID: string): $CancellablePromise<registry$0.DownloadStats | null> {
    return $Call.ByID(1152913314, pluginID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPluginMeta(id: string): $CancellablePromise<config$0.PluginMeta> {
    return $Call.ByID(111194374, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPluginReadme(pluginID: string): $CancellablePromise<string> {
    return $Call.ByID(3945933305, pluginID);
}

export function GetPluginReleaseHistory(pluginID: string): $CancellablePromise<registry$0.VersionInfo[]> {
    return $Call.ByID(2859775056, pluginID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPluginReviews(pluginID: string, page: number): $CancellablePromise<registry$0.Review[]> {
    return $Call.ByID(2209599792, pluginID, page).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetPluginVersions(pluginID: string): $CancellablePromise<registry$0.VersionInfo[]> {
    return $Call.ByID(3963363730, pluginID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function InstallFromPathPrompt(): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(2477486666).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallInDevMode(): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(976517756).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallPluginFromPath(path: string): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(1020548995, path).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallPluginVersion(pluginID: string, version: string): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(2004740384, pluginID, version).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListAvailablePlugins(): $CancellablePromise<registry$0.AvailablePlugin[]> {
    return $Call.ByID(873697101).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListPluginMetas(): $CancellablePromise<config$0.PluginMeta[]> {
    return $Call.ByID(637134283).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListPlugins(): $CancellablePromise<types$0.PluginInfo[]> {
    return $Call.ByID(550607756).then(($result: any) => {
        return $$createType12($result);
    });
}

export function LoadPlugin(id: string, opts: $models.LoadPluginOptions | null): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(288660195, id, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReloadPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(1771013494, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RetryFailedPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(2433379724, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SearchPlugins(query: string, category: string, sort: string): $CancellablePromise<registry$0.AvailablePlugin[]> {
    return $Call.ByID(2783597264, query, category, sort).then(($result: any) => {
        return $$createType10($result);
    });
}

export function UninstallPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(1369550929, id).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.PluginInfo.createFrom;
const $$createType1 = registry$0.DownloadStats.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.PluginMeta.createFrom;
const $$createType4 = registry$0.VersionInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = registry$0.Review.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Nullable($$createType3);
const $$createType9 = registry$0.AvailablePlugin.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType3);
const $$createType12 = $Create.Array($$createType0);
