// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceWrapper is an explicit delegation wrapper around resource.Controller.
 * Excluded: OnPluginInit, OnPluginStart, OnPluginStop, OnPluginShutdown,
 * 
 * 	OnPluginDestroy, Run, SetCrashCallback, Graph
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../../../plugin-sdk/pkg/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../../../../../plugin-sdk/pkg/v1/resource/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddConnection(pluginID: string, connection: types$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(4065522324, pluginID, connection);
}

export function CheckConnection(pluginID: string, connectionID: string): $CancellablePromise<types$0.ConnectionStatus> {
    return $Call.ByID(1688967279, pluginID, connectionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Create(pluginID: string, connectionID: string, key: string, input: resource$0.CreateInput): $CancellablePromise<resource$0.CreateResult | null> {
    return $Call.ByID(1613386605, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Delete(pluginID: string, connectionID: string, key: string, input: resource$0.DeleteInput): $CancellablePromise<resource$0.DeleteResult | null> {
    return $Call.ByID(1477526970, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function EnsureResourceWatch(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<void> {
    return $Call.ByID(1338477906, pluginID, connectionID, resourceKey);
}

export function ExecuteAction(pluginID: string, connectionID: string, key: string, actionID: string, input: resource$0.ActionInput): $CancellablePromise<resource$0.ActionResult | null> {
    return $Call.ByID(1844283666, pluginID, connectionID, key, actionID, input).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Find(pluginID: string, connectionID: string, key: string, input: resource$0.FindInput): $CancellablePromise<resource$0.FindResult | null> {
    return $Call.ByID(4148812394, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * CRUD
 */
export function Get(pluginID: string, connectionID: string, key: string, input: resource$0.GetInput): $CancellablePromise<resource$0.GetResult | null> {
    return $Call.ByID(194970279, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Actions
 */
export function GetActions(pluginID: string, connectionID: string, key: string): $CancellablePromise<resource$0.ActionDescriptor[]> {
    return $Call.ByID(419011114, pluginID, connectionID, key).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetAllConnectionStates(): $CancellablePromise<{ [_ in string]?: $models.ConnectionState[] }> {
    return $Call.ByID(4153677080).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetConnection(pluginID: string, connectionID: string): $CancellablePromise<types$0.Connection> {
    return $Call.ByID(950535743, pluginID, connectionID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetConnectionNamespaces(pluginID: string, connectionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(537508515, pluginID, connectionID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Editor schemas
 */
export function GetEditorSchemas(pluginID: string, connectionID: string): $CancellablePromise<resource$0.EditorSchema[]> {
    return $Call.ByID(1394342402, pluginID, connectionID).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetFilterFields(pluginID: string, connectionID: string, key: string): $CancellablePromise<resource$0.FilterField[]> {
    return $Call.ByID(1947262600, pluginID, connectionID, key).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * Health
 */
export function GetHealth(pluginID: string, connectionID: string, key: string, data: json$0.RawMessage): $CancellablePromise<resource$0.ResourceHealth | null> {
    return $Call.ByID(1644192689, pluginID, connectionID, key, data).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * Relationships
 */
export function GetRelationships(pluginID: string, key: string): $CancellablePromise<resource$0.RelationshipDescriptor[]> {
    return $Call.ByID(2699561690, pluginID, key).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetResourceCapabilities(pluginID: string, key: string): $CancellablePromise<resource$0.ResourceCapabilities | null> {
    return $Call.ByID(1474609809, pluginID, key).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetResourceDefinition(pluginID: string, typeID: string): $CancellablePromise<resource$0.ResourceDefinition> {
    return $Call.ByID(4077050094, pluginID, typeID).then(($result: any) => {
        return $$createType28($result);
    });
}

export function GetResourceEvents(pluginID: string, connectionID: string, key: string, id: string, $namespace: string, limit: number): $CancellablePromise<resource$0.ResourceEvent[]> {
    return $Call.ByID(3171791798, pluginID, connectionID, key, id, $namespace, limit).then(($result: any) => {
        return $$createType30($result);
    });
}

export function GetResourceGroup(pluginID: string, groupID: string): $CancellablePromise<resource$0.ResourceGroup> {
    return $Call.ByID(114848330, pluginID, groupID).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * Type metadata
 */
export function GetResourceGroups(pluginID: string, connectionID: string): $CancellablePromise<{ [_ in string]?: resource$0.ResourceGroup }> {
    return $Call.ByID(4290498491, pluginID, connectionID).then(($result: any) => {
        return $$createType32($result);
    });
}

export function GetResourceSchema(pluginID: string, connectionID: string, key: string): $CancellablePromise<json$0.RawMessage> {
    return $Call.ByID(137675652, pluginID, connectionID, key);
}

export function GetResourceType(pluginID: string, typeID: string): $CancellablePromise<resource$0.ResourceMeta | null> {
    return $Call.ByID(2078766795, pluginID, typeID).then(($result: any) => {
        return $$createType34($result);
    });
}

export function GetResourceTypes(pluginID: string, connectionID: string): $CancellablePromise<{ [_ in string]?: resource$0.ResourceMeta }> {
    return $Call.ByID(3311395752, pluginID, connectionID).then(($result: any) => {
        return $$createType35($result);
    });
}

export function GetWatchState(pluginID: string, connectionID: string): $CancellablePromise<resource$0.WatchConnectionSummary | null> {
    return $Call.ByID(42345827, pluginID, connectionID).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * HasPlugin
 */
export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(854008408, pluginID);
}

export function HasResourceType(pluginID: string, typeID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3547410887, pluginID, typeID);
}

export function IsResourceWatchRunning(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<boolean> {
    return $Call.ByID(3516169863, pluginID, connectionID, resourceKey);
}

export function List(pluginID: string, connectionID: string, key: string, input: resource$0.ListInput): $CancellablePromise<resource$0.ListResult | null> {
    return $Call.ByID(3093409425, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType39($result);
    });
}

export function ListAllConnections(): $CancellablePromise<{ [_ in string]?: types$0.Connection[] }> {
    return $Call.ByID(1598984489).then(($result: any) => {
        return $$createType41($result);
    });
}

export function ListConnections(pluginID: string): $CancellablePromise<types$0.Connection[]> {
    return $Call.ByID(1775572154, pluginID).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * ListPlugins
 */
export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(3217612415).then(($result: any) => {
        return $$createType17($result);
    });
}

export function LoadConnections(pluginID: string): $CancellablePromise<types$0.Connection[]> {
    return $Call.ByID(2037329938, pluginID).then(($result: any) => {
        return $$createType40($result);
    });
}

export function RemoveConnection(pluginID: string, connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(421198049, pluginID, connectionID);
}

export function ResolveRelationships(pluginID: string, connectionID: string, key: string, id: string, $namespace: string): $CancellablePromise<resource$0.ResolvedRelationship[]> {
    return $Call.ByID(3987850310, pluginID, connectionID, key, id, $namespace).then(($result: any) => {
        return $$createType43($result);
    });
}

export function RestartResourceWatch(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<void> {
    return $Call.ByID(555702059, pluginID, connectionID, resourceKey);
}

/**
 * Connection lifecycle
 */
export function StartConnection(pluginID: string, connectionID: string): $CancellablePromise<types$0.ConnectionStatus> {
    return $Call.ByID(3276991559, pluginID, connectionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Watch lifecycle
 */
export function StartConnectionWatch(pluginID: string, connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3389223006, pluginID, connectionID);
}

export function StopConnection(pluginID: string, connectionID: string): $CancellablePromise<types$0.Connection> {
    return $Call.ByID(794258089, pluginID, connectionID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function StopConnectionWatch(pluginID: string, connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1661153284, pluginID, connectionID);
}

export function StopResourceWatch(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<void> {
    return $Call.ByID(3981374696, pluginID, connectionID, resourceKey);
}

export function StreamAction(pluginID: string, connectionID: string, key: string, actionID: string, input: resource$0.ActionInput): $CancellablePromise<string> {
    return $Call.ByID(2990116431, pluginID, connectionID, key, actionID, input);
}

/**
 * Subscriptions
 */
export function SubscribeResource(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<void> {
    return $Call.ByID(2856546527, pluginID, connectionID, resourceKey);
}

export function UnsubscribeResource(pluginID: string, connectionID: string, resourceKey: string): $CancellablePromise<void> {
    return $Call.ByID(3710015102, pluginID, connectionID, resourceKey);
}

export function Update(pluginID: string, connectionID: string, key: string, input: resource$0.UpdateInput): $CancellablePromise<resource$0.UpdateResult | null> {
    return $Call.ByID(2408192164, pluginID, connectionID, key, input).then(($result: any) => {
        return $$createType45($result);
    });
}

export function UpdateConnection(pluginID: string, connection: types$0.Connection): $CancellablePromise<types$0.Connection> {
    return $Call.ByID(2131988692, pluginID, connection).then(($result: any) => {
        return $$createType16($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.ConnectionStatus.createFrom;
const $$createType1 = resource$0.CreateResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = resource$0.DeleteResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = resource$0.ActionResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = resource$0.FindResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = resource$0.GetResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = resource$0.ActionDescriptor.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.ConnectionState.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = types$0.Connection.createFrom;
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = resource$0.EditorSchema.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = resource$0.FilterField.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = resource$0.ResourceHealth.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = resource$0.RelationshipDescriptor.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = resource$0.ResourceCapabilities.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = resource$0.ResourceDefinition.createFrom;
const $$createType29 = resource$0.ResourceEvent.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = resource$0.ResourceGroup.createFrom;
const $$createType32 = $Create.Map($Create.Any, $$createType31);
const $$createType33 = resource$0.ResourceMeta.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = $Create.Map($Create.Any, $$createType33);
const $$createType36 = resource$0.WatchConnectionSummary.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = resource$0.ListResult.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $Create.Array($$createType16);
const $$createType41 = $Create.Map($Create.Any, $$createType40);
const $$createType42 = resource$0.ResolvedRelationship.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = resource$0.UpdateResult.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
