export const logoMap: { [key: string]: string } = {
  alertmanager: "SiPrometheus",
  aws: "SiAmazonaws",
  "aws-node": "SiAmazonaws",
  "aws-cli": "SiAmazonaws",
  "aws-eks-nodeagent": "SiAmazoneks",
  "aws-load-balancer-controller":
    "https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/assets/images/aws_load_balancer_icon.svg",
  "cloudflare-exporter": "SiCloudflare",
  "cloudwatch-exporter": "SiAmazoncloudwatch",
  coredns: "https://avatars.githubusercontent.com/u/21110084?s=280&v=4",
  "ebs-csi": "SiAmazonaws",
  "ebs-csi-driver": "SiAmazonaws",
  "ebs-plugin": "SiAmazonaws",
  "efs-csi": "SiAmazonaws",
  "efs-csi-driver": "SiAmazonaws",
  "efs-plugin": "SiAmazonaws",
  "external-dns":
    "https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png",
  go: "SiGo",
  golang: "SiGo",
  java: "SiJava",
  jnlp: "SiJenkins",
  jenkins: "SiJenkins",
  jenkinsx: "SiJenkinsx",
  "kube-proxy": "SiKubernetes",
  nginx:
    "https://www.nginx.com/wp-content/uploads/2020/05/NGINX-product-icon.svg",
  "nginx-ingress-controller":
    "https://www.nginx.com/wp-content/uploads/2020/05/NGINX-product-icon.svg",
  "nginx-ingress":
    "https://www.nginx.com/wp-content/uploads/2020/05/NGINX-product-icon.svg",
  node: "SiNodedotjs",
  grafana: "SiGrafana",
  "grafana-agent":
    "https://github-production-user-asset-6210df.s3.amazonaws.com/223048/257522425-48683963-91ae-4caf-8c52-ce131e25bd65.png",
  "grafana-agent-operator":
    "https://github-production-user-asset-6210df.s3.amazonaws.com/223048/257522425-48683963-91ae-4caf-8c52-ce131e25bd65.png",
  mimir: "https://grafana.com/static/img/logos/logo-mimir.svg",
  "metrics-server": "SiKubernetes",
  promtail: "https://files.readme.io/e5e1b43-grafana-loki.png",
  loki: "https://files.readme.io/e5e1b43-grafana-loki.png",
  tempo: "https://grafana.com/static/img/menu/grafana-tempo.svg",
  "node-exporter": "SiPrometheus",
  prometheus: "SiPrometheus",
  postgres: "SiPostgresql",
  postgresql: "SiPostgresql",
  redis: "SiRedis",
  mariadb: "SiMariadb",
  mysql: "SiMysql",
  mongo: "SiMongodb",
  mongodb: "SiMongodb",
  php: "SiPhp",
  "php-fpm": "SiPhp",
  phpfpm: "SiPhp",
  python: "SiPython",
  ruby: "SiRuby",
  rust: "SiRust",
  sonarqube: "https://cdn.worldvectorlogo.com/logos/sonarqube-1.svg",
  swift: "SiSwift",
  csharp: "SiCsharp",
  dotnet: "SiDotnet",
  dotnetcore: "SiDotnet",
  "dotnet-core": "SiDotnet",
  trivy:
    "https://desktop.docker.com/extensions/aquasec_trivy-docker-extension/raw_githubusercontent_com/aquasecurity/trivy-docker-extension/main/trivy.svg",
};
