// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Delete(pluginID: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(2784630898, pluginID, key);
}

export function Get(pluginID: string, key: string): $CancellablePromise<any> {
    return $Call.ByID(1249901663, pluginID, key);
}

export function Keys(pluginID: string): $CancellablePromise<string[]> {
    return $Call.ByID(1862041893, pluginID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Set(pluginID: string, key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(1059399179, pluginID, key, value);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
