// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevServerService exposes only frontend-safe methods of devserver.DevServerManager.
 * The DevServerManager implements ServiceStartup/ServiceShutdown directly,
 * but registering it raw causes service/model shadowing. This wrapper separates
 * the service identity from the model type.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as devserver$0 from "./backend/pkg/plugin/devserver/models.js";

export function GetDevServerLogs(pluginID: string, count: number): $CancellablePromise<devserver$0.LogEntry[]> {
    return $Call.ByID(56031670, pluginID, count).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDevServerState(pluginID: string): $CancellablePromise<devserver$0.DevServerState> {
    return $Call.ByID(2931579078, pluginID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetExternalPluginInfo(pluginID: string): $CancellablePromise<devserver$0.DevInfoFile | null> {
    return $Call.ByID(4231701063, pluginID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function IsManaged(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1031994258, pluginID);
}

export function ListDevServerStates(): $CancellablePromise<devserver$0.DevServerState[]> {
    return $Call.ByID(3754746401).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RebuildPlugin(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(4157478183, pluginID);
}

export function RestartDevServer(pluginID: string): $CancellablePromise<devserver$0.DevServerState> {
    return $Call.ByID(2240108516, pluginID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartDevServer(pluginID: string): $CancellablePromise<devserver$0.DevServerState> {
    return $Call.ByID(843165717, pluginID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartDevServerForPath(pluginID: string, devPath: string): $CancellablePromise<devserver$0.DevServerState> {
    return $Call.ByID(4039660679, pluginID, devPath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StopDevServer(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(1563164227, pluginID);
}

// Private type creation functions
const $$createType0 = devserver$0.LogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = devserver$0.DevServerState.createFrom;
const $$createType3 = devserver$0.DevInfoFile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType2);
