// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogsControllerService wraps the pluginlogs.Controller interface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./backend/pkg/plugin/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../plugin-sdk/pkg/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logs$0 from "../plugin-sdk/pkg/v1/logs/models.js";

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3286870078, sessionID);
}

export function CreateSession(plugin: string, connectionID: string, opts: logs$0.CreateSessionOptions): $CancellablePromise<logs$0.LogSession | null> {
    return $Call.ByID(1710486702, plugin, connectionID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSession(sessionID: string): $CancellablePromise<logs$0.LogSession | null> {
    return $Call.ByID(365161342, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSupportedResources(pluginID: string): $CancellablePromise<logs$0.Handler[]> {
    return $Call.ByID(1885041493, pluginID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * HasPlugin returns true if the plugin is registered with this controller.
 */
export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(34226137, pluginID);
}

/**
 * ListPlugins returns a list of names of the plugins that are installed.
 */
export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(3747829186).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListSessions(): $CancellablePromise<(logs$0.LogSession | null)[]> {
    return $Call.ByID(4219296599).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OnPluginDestroy is called when the plugin is being removed from the system. This is the last chance to
 * clean up any resources associated with the plugin before it is uninstalled.
 */
export function OnPluginDestroy(pluginID: string, meta: config$0.PluginMeta): $CancellablePromise<void> {
    return $Call.ByID(984696990, pluginID, meta);
}

/**
 * OnPluginInit is called after the plugin is loaded in to do any pre-startup initialization.
 */
export function OnPluginInit(pluginID: string, meta: config$0.PluginMeta): $CancellablePromise<void> {
    return $Call.ByID(1358758862, pluginID, meta);
}

/**
 * OnPluginShutdown is called when the plugin is shutdown. This is the last chance to clean up any resources
 * before the IDE is closed.
 */
export function OnPluginShutdown(pluginID: string, meta: config$0.PluginMeta): $CancellablePromise<void> {
    return $Call.ByID(2701368150, pluginID, meta);
}

/**
 * OnPluginStart is called when the plugin is started.
 */
export function OnPluginStart(pluginID: string, meta: config$0.PluginMeta, backend: types$0.PluginBackend): $CancellablePromise<void> {
    return $Call.ByID(1254747760, pluginID, meta, backend);
}

/**
 * OnPluginStop is called when the plugin is stopped. Modules should perform any persisting of state here
 */
export function OnPluginStop(pluginID: string, meta: config$0.PluginMeta): $CancellablePromise<void> {
    return $Call.ByID(1707741172, pluginID, meta);
}

export function SendCommand(sessionID: string, cmd: logs$0.LogStreamCommand): $CancellablePromise<void> {
    return $Call.ByID(4186946429, sessionID, cmd);
}

export function UpdateSessionOptions(sessionID: string, opts: logs$0.LogSessionOptions): $CancellablePromise<logs$0.LogSession | null> {
    return $Call.ByID(4077718521, sessionID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = logs$0.LogSession.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = logs$0.Handler.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType1);
