// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metric$0 from "./backend/pkg/plugin/metric/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metric$1 from "../plugin-sdk/pkg/v1/metric/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export function GetProviders(): $CancellablePromise<metric$0.MetricProviderSummary[]> {
    return $Call.ByID(2838019531).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetProvidersForResource(resourceKey: string): $CancellablePromise<metric$0.MetricProviderSummary[]> {
    return $Call.ByID(643157078, resourceKey).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HasPlugin(pluginID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3044575076, pluginID);
}

export function ListPlugins(): $CancellablePromise<string[]> {
    return $Call.ByID(162304859).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Query(pluginID: string, connectionID: string, req: metric$1.QueryRequest): $CancellablePromise<metric$1.QueryResponse | null> {
    return $Call.ByID(3357897247, pluginID, connectionID, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function QueryAll(connectionID: string, resourceKey: string, resourceID: string, $namespace: string, resourceData: { [_ in string]?: any }, metricIDs: string[], shape: metric$1.MetricShape, startTime: time$0.Time, endTime: time$0.Time, step: time$0.Duration): $CancellablePromise<{ [_ in string]?: metric$1.QueryResponse | null }> {
    return $Call.ByID(2842472394, connectionID, resourceKey, resourceID, $namespace, resourceData, metricIDs, shape, startTime, endTime, step).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Subscribe(pluginID: string, connectionID: string, req: metric$0.SubscribeRequest): $CancellablePromise<string> {
    return $Call.ByID(320253359, pluginID, connectionID, req);
}

export function Unsubscribe(subscriptionID: string): $CancellablePromise<void> {
    return $Call.ByID(715373378, subscriptionID);
}

// Private type creation functions
const $$createType0 = metric$0.MetricProviderSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = metric$1.QueryResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
