// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginManagerService exposes only the frontend-safe methods of plugin.Manager.
 * Internal methods (SetDevServerChecker, SetPluginLogManager, HandlePluginCrash,
 * Initialize, Run, Shutdown) are excluded to avoid binding warnings from
 * interface/function-type parameters.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "./backend/pkg/plugin/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as registry$0 from "./backend/pkg/plugin/registry/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../plugin-sdk/pkg/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../plugin-sdk/pkg/types/models.js";

export function GetPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(4036673098, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPluginDownloadStats(pluginID: string): $CancellablePromise<registry$0.DownloadStats | null> {
    return $Call.ByID(2726517273, pluginID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPluginMeta(id: string): $CancellablePromise<config$0.PluginMeta> {
    return $Call.ByID(499197031, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPluginReadme(pluginID: string): $CancellablePromise<string> {
    return $Call.ByID(2763449240, pluginID);
}

export function GetPluginReleaseHistory(pluginID: string): $CancellablePromise<registry$0.VersionInfo[]> {
    return $Call.ByID(1156861621, pluginID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPluginReviews(pluginID: string, page: number): $CancellablePromise<registry$0.Review[]> {
    return $Call.ByID(933402483, pluginID, page).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetPluginVersions(pluginID: string): $CancellablePromise<registry$0.VersionInfo[]> {
    return $Call.ByID(997632447, pluginID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function InstallFromPathPrompt(): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(467309803).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallInDevMode(): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(830591135).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallPluginFromPath(path: string): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(1186389510, path).then(($result: any) => {
        return $$createType8($result);
    });
}

export function InstallPluginVersion(pluginID: string, version: string): $CancellablePromise<config$0.PluginMeta | null> {
    return $Call.ByID(2959706071, pluginID, version).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListAvailablePlugins(): $CancellablePromise<registry$0.AvailablePlugin[]> {
    return $Call.ByID(588186274).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListPluginMetas(): $CancellablePromise<config$0.PluginMeta[]> {
    return $Call.ByID(3279236650).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListPlugins(): $CancellablePromise<types$0.PluginInfo[]> {
    return $Call.ByID(1059385665).then(($result: any) => {
        return $$createType12($result);
    });
}

export function LoadPlugin(id: string, opts: plugin$0.LoadPluginOptions | null): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(815485296, id, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReloadPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(3455220157, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RetryFailedPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(4058095161, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SearchPlugins(query: string, category: string, sort: string): $CancellablePromise<registry$0.AvailablePlugin[]> {
    return $Call.ByID(4050877057, query, category, sort).then(($result: any) => {
        return $$createType10($result);
    });
}

export function UninstallPlugin(id: string): $CancellablePromise<types$0.PluginInfo> {
    return $Call.ByID(1540344876, id).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = types$0.PluginInfo.createFrom;
const $$createType1 = registry$0.DownloadStats.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.PluginMeta.createFrom;
const $$createType4 = registry$0.VersionInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = registry$0.Review.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Nullable($$createType3);
const $$createType9 = registry$0.AvailablePlugin.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType3);
const $$createType12 = $Create.Array($$createType0);
