// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../plugin-sdk/settings/models.js";

export function GetBool(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(199975759, id);
}

export function GetCategories(): $CancellablePromise<settings$0.Category[]> {
    return $Call.ByID(1339187527).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCategory(id: string): $CancellablePromise<settings$0.Category> {
    return $Call.ByID(2732589519, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCategoryValues(id: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3158210645, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetFloat(id: string): $CancellablePromise<number> {
    return $Call.ByID(3278855775, id);
}

export function GetFloatSlice(id: string): $CancellablePromise<number[]> {
    return $Call.ByID(588704383, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetInt(id: string): $CancellablePromise<number> {
    return $Call.ByID(3084011556, id);
}

export function GetIntSlice(id: string): $CancellablePromise<number[]> {
    return $Call.ByID(1052115198, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSetting(id: string): $CancellablePromise<settings$0.Setting> {
    return $Call.ByID(250150593, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSettingValue(id: string): $CancellablePromise<any> {
    return $Call.ByID(4025421518, id);
}

export function GetString(id: string): $CancellablePromise<string> {
    return $Call.ByID(1187755918, id);
}

export function GetStringSlice(id: string): $CancellablePromise<string[]> {
    return $Call.ByID(1832879132, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListSettings(): $CancellablePromise<settings$0.Store> {
    return $Call.ByID(89725144).then(($result: any) => {
        return $$createType7($result);
    });
}

export function LoadSettings(): $CancellablePromise<void> {
    return $Call.ByID(2308717928);
}

export function ResetSetting(id: string): $CancellablePromise<void> {
    return $Call.ByID(2245976448, id);
}

export function SaveSettings(): $CancellablePromise<void> {
    return $Call.ByID(3807115937);
}

export function SetSetting(id: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(2825655029, id, value);
}

export function SetSettings(settingsMap: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(2820745458, settingsMap);
}

export function Values(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3413962943).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = settings$0.Category.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = settings$0.Setting.createFrom;
const $$createType6 = $Create.Array($Create.Any);
var $$createType7 = (function $$initCreateType7(...args: any[]): any {
    if ($$createType7 === $$initCreateType7) {
        $$createType7 = $$createType8;
    }
    return $$createType7(...args);
});
const $$createType8 = $Create.Map($Create.Any, $$createType0);
