// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {exec} from '../models';

export function AttachSession(arg1:string):Promise<exec.AttachSessionResult>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string,arg3:exec.SessionOptions):Promise<exec.Session>;

export function CreateTerminal(arg1:exec.CreateTerminalOptions):Promise<exec.Session>;

export function DetachSession(arg1:string):Promise<exec.Session>;

export function GetHandler(arg1:string,arg2:string):Promise<exec.HandlerOpts>;

export function GetHandlers():Promise<{[key: string]: {[key: string]: exec.HandlerOpts}}>;

export function GetPluginHandlers(arg1:string):Promise<{[key: string]: exec.HandlerOpts}>;

export function GetSession(arg1:string):Promise<exec.Session>;

export function ListPlugins():Promise<Array<string>>;

export function ListSessions():Promise<Array<exec.Session>>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;
