// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../../../../../../plugin-sdk/pkg/v1/resource/models.js";

export class DependencyNode {
    "edge": GraphEdge;
    "children": DependencyNode[];

    /** Creates a new DependencyNode instance. */
    constructor($$source: Partial<DependencyNode> = {}) {
        if (!("edge" in $$source)) {
            this["edge"] = (new GraphEdge());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyNode {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edge" in $$parsedSource) {
            $$parsedSource["edge"] = $$createField0_0($$parsedSource["edge"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new DependencyNode($$parsedSource as Partial<DependencyNode>);
    }
}

export class DependencyTree {
    "root": GraphNode;
    "children": DependencyNode[];

    /** Creates a new DependencyTree instance. */
    constructor($$source: Partial<DependencyTree> = {}) {
        if (!("root" in $$source)) {
            this["root"] = (new GraphNode());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyTree instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyTree {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("root" in $$parsedSource) {
            $$parsedSource["root"] = $$createField0_0($$parsedSource["root"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new DependencyTree($$parsedSource as Partial<DependencyTree>);
    }
}

export class GraphEdge {
    "source": GraphNode;
    "target": GraphNode;
    "type": RelationshipType;
    "label": string;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("source" in $$source)) {
            this["source"] = (new GraphNode());
        }
        if (!("target" in $$source)) {
            this["target"] = (new GraphNode());
        }
        if (!("type" in $$source)) {
            this["type"] = resource$0.RelationshipType.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField0_0($$parsedSource["source"]);
        }
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField1_0($$parsedSource["target"]);
        }
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode identifies a specific resource instance in the graph.
 */
export class GraphNode {
    "pluginId": string;
    "connectionId": string;
    "resourceKey": string;
    "id": string;
    "namespace"?: string;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("resourceKey" in $$source)) {
            this["resourceKey"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

/**
 * RelationshipType re-exports from SDK for convenience.
 */
export type RelationshipType = resource$0.RelationshipType;

// Private type creation functions
const $$createType0 = GraphEdge.createFrom;
const $$createType1 = DependencyNode.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = GraphNode.createFrom;
