// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPluginComponents(arg1) {
  return window['go']['ui']['Client']['GetPluginComponents'](arg1);
}

export function GetResourceAreaComponent(arg1) {
  return window['go']['ui']['Client']['GetResourceAreaComponent'](arg1);
}

export function GetResourceComponents(arg1) {
  return window['go']['ui']['Client']['GetResourceComponents'](arg1);
}
