// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {config} from '../models';
import {context} from '../models';

export function GetPlugin(arg1:string):Promise<types.Plugin>;

export function GetPluginMeta(arg1:string):Promise<config.PluginMeta>;

export function Initialize(arg1:context.Context):Promise<void>;

export function InstallFromPathPrompt():Promise<config.PluginMeta>;

export function InstallPluginFromPath(arg1:string):Promise<config.PluginMeta>;

export function ListPluginMetas():Promise<Array<config.PluginMeta>>;

export function ListPlugins():Promise<Array<types.Plugin>>;

export function LoadPlugin(arg1:string):Promise<types.Plugin>;

export function ReloadPlugin(arg1:string):Promise<types.Plugin>;

export function UninstallPlugin(arg1:string):Promise<types.Plugin>;

export function UnloadPlugin(arg1:string):Promise<void>;
