// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['logs']['Client']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['logs']['Client']['CreateSession'](arg1, arg2, arg3);
}

export function GetSession(arg1) {
  return window['go']['logs']['Client']['GetSession'](arg1);
}

export function GetSupportedResources(arg1) {
  return window['go']['logs']['Client']['GetSupportedResources'](arg1);
}

export function ListSessions() {
  return window['go']['logs']['Client']['ListSessions']();
}

export function PauseSession(arg1) {
  return window['go']['logs']['Client']['PauseSession'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['logs']['Client']['ResumeSession'](arg1);
}

export function UpdateSessionOptions(arg1, arg2) {
  return window['go']['logs']['Client']['UpdateSessionOptions'](arg1, arg2);
}
