// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * ActionTargetBuilder builds a dynamic list of targets for an action.
 */
export class ActionTargetBuilder {
    "label": string;
    "label_selector": string;
    "paths": string[];
    "selectors": { [_ in string]?: string };

    /** Creates a new ActionTargetBuilder instance. */
    constructor($$source: Partial<ActionTargetBuilder> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("label_selector" in $$source)) {
            this["label_selector"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("selectors" in $$source)) {
            this["selectors"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionTargetBuilder instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionTargetBuilder {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField2_0($$parsedSource["paths"]);
        }
        if ("selectors" in $$parsedSource) {
            $$parsedSource["selectors"] = $$createField3_0($$parsedSource["selectors"]);
        }
        return new ActionTargetBuilder($$parsedSource as Partial<ActionTargetBuilder>);
    }
}

/**
 * Handler handles running commands and creating sessions for a resource.
 */
export class Handler {
    "plugin": string;
    "resource": string;
    "target_builder": ActionTargetBuilder;
    "default_command": string[];

    /** Creates a new Handler instance. */
    constructor($$source: Partial<Handler> = {}) {
        if (!("plugin" in $$source)) {
            this["plugin"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("target_builder" in $$source)) {
            this["target_builder"] = (new ActionTargetBuilder());
        }
        if (!("default_command" in $$source)) {
            this["default_command"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Handler instance from a string or object.
     */
    static createFrom($$source: any = {}): Handler {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target_builder" in $$parsedSource) {
            $$parsedSource["target_builder"] = $$createField2_0($$parsedSource["target_builder"]);
        }
        if ("default_command" in $$parsedSource) {
            $$parsedSource["default_command"] = $$createField3_0($$parsedSource["default_command"]);
        }
        return new Handler($$parsedSource as Partial<Handler>);
    }
}

/**
 * Session is a snapshot value type — safe for concurrent reads, returned by
 * the public API. It carries no mutable internal state.
 */
export class Session {
    "created_at": time$0.Time;
    "labels": { [_ in string]?: string };
    "params": { [_ in string]?: string };
    "id": string;
    "command": string[];
    "attached": boolean;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }
        if (!("params" in $$source)) {
            this["params"] = {};
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = [];
        }
        if (!("attached" in $$source)) {
            this["attached"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField2_0($$parsedSource["params"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField4_0($$parsedSource["command"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

/**
 * SessionOptions contains options for creating a new terminal session.
 */
export class SessionOptions {
    "params": { [_ in string]?: string };
    "labels": { [_ in string]?: string };
    "id": string;
    "resource_plugin": string;
    "resource_key": string;
    "resource_data": { [_ in string]?: any };
    "command": string[];
    "tty": boolean;

    /** Creates a new SessionOptions instance. */
    constructor($$source: Partial<SessionOptions> = {}) {
        if (!("params" in $$source)) {
            this["params"] = {};
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("resource_plugin" in $$source)) {
            this["resource_plugin"] = "";
        }
        if (!("resource_key" in $$source)) {
            this["resource_key"] = "";
        }
        if (!("resource_data" in $$source)) {
            this["resource_data"] = {};
        }
        if (!("command" in $$source)) {
            this["command"] = [];
        }
        if (!("tty" in $$source)) {
            this["tty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionOptions {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField0_0($$parsedSource["params"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        if ("resource_data" in $$parsedSource) {
            $$parsedSource["resource_data"] = $$createField5_0($$parsedSource["resource_data"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField6_0($$parsedSource["command"]);
        }
        return new SessionOptions($$parsedSource as Partial<SessionOptions>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ActionTargetBuilder.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
