// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeStreamResponse_Status int32

const (
	SubscribeStreamResponse_OK                SubscribeStreamResponse_Status = 0
	SubscribeStreamResponse_NOT_FOUND         SubscribeStreamResponse_Status = 1
	SubscribeStreamResponse_PERMISSION_DENIED SubscribeStreamResponse_Status = 2
)

// Enum value maps for SubscribeStreamResponse_Status.
var (
	SubscribeStreamResponse_Status_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "PERMISSION_DENIED",
	}
	SubscribeStreamResponse_Status_value = map[string]int32{
		"OK":                0,
		"NOT_FOUND":         1,
		"PERMISSION_DENIED": 2,
	}
)

func (x SubscribeStreamResponse_Status) Enum() *SubscribeStreamResponse_Status {
	p := new(SubscribeStreamResponse_Status)
	*p = x
	return p
}

func (x SubscribeStreamResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeStreamResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_proto_enumTypes[0].Descriptor()
}

func (SubscribeStreamResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_command_proto_enumTypes[0]
}

func (x SubscribeStreamResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeStreamResponse_Status.Descriptor instead.
func (SubscribeStreamResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{5, 0}
}

type PublishStreamResponse_Status int32

const (
	PublishStreamResponse_OK                PublishStreamResponse_Status = 0
	PublishStreamResponse_NOT_FOUND         PublishStreamResponse_Status = 1
	PublishStreamResponse_PERMISSION_DENIED PublishStreamResponse_Status = 2
)

// Enum value maps for PublishStreamResponse_Status.
var (
	PublishStreamResponse_Status_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "PERMISSION_DENIED",
	}
	PublishStreamResponse_Status_value = map[string]int32{
		"OK":                0,
		"NOT_FOUND":         1,
		"PERMISSION_DENIED": 2,
	}
)

func (x PublishStreamResponse_Status) Enum() *PublishStreamResponse_Status {
	p := new(PublishStreamResponse_Status)
	*p = x
	return p
}

func (x PublishStreamResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStreamResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_proto_enumTypes[1].Descriptor()
}

func (PublishStreamResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_command_proto_enumTypes[1]
}

func (x PublishStreamResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStreamResponse_Status.Descriptor instead.
func (PublishStreamResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{7, 0}
}

type PluginContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source plugin calling the API.
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// settings for the plugin
	PluginSettings map[string]string `protobuf:"bytes,2,rep,name=plugin_settings,json=pluginSettings,proto3" json:"plugin_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// global IDE settings
	GlobalSettings map[string]string `protobuf:"bytes,3,rep,name=global_settings,json=globalSettings,proto3" json:"global_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginContext) Reset() {
	*x = PluginContext{}
	mi := &file_proto_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginContext) ProtoMessage() {}

func (x *PluginContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginContext.ProtoReflect.Descriptor instead.
func (*PluginContext) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{0}
}

func (x *PluginContext) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginContext) GetPluginSettings() map[string]string {
	if x != nil {
		return x.PluginSettings
	}
	return nil
}

func (x *PluginContext) GetGlobalSettings() map[string]string {
	if x != nil {
		return x.GlobalSettings
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_proto_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CallCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginContext *PluginContext         `protobuf:"bytes,1,opt,name=plugin_context,json=pluginContext,proto3" json:"plugin_context,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCommandRequest) Reset() {
	*x = CallCommandRequest{}
	mi := &file_proto_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCommandRequest) ProtoMessage() {}

func (x *CallCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCommandRequest.ProtoReflect.Descriptor instead.
func (*CallCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{2}
}

func (x *CallCommandRequest) GetPluginContext() *PluginContext {
	if x != nil {
		return x.PluginContext
	}
	return nil
}

func (x *CallCommandRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallCommandRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallCommandRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CallCommandRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallCommandRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type CallCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCommandResponse) Reset() {
	*x = CallCommandResponse{}
	mi := &file_proto_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCommandResponse) ProtoMessage() {}

func (x *CallCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCommandResponse.ProtoReflect.Descriptor instead.
func (*CallCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{3}
}

func (x *CallCommandResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CallCommandResponse) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallCommandResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type SubscribeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginContext *PluginContext         `protobuf:"bytes,1,opt,name=plugin_context,json=pluginContext,proto3" json:"plugin_context,omitempty"`
	// path part of channel.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStreamRequest) Reset() {
	*x = SubscribeStreamRequest{}
	mi := &file_proto_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStreamRequest) ProtoMessage() {}

func (x *SubscribeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStreamRequest.ProtoReflect.Descriptor instead.
func (*SubscribeStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeStreamRequest) GetPluginContext() *PluginContext {
	if x != nil {
		return x.PluginContext
	}
	return nil
}

func (x *SubscribeStreamRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SubscribeStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status of subscribe response.
	Status SubscribeStreamResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=com.omniview.pluginsdk.SubscribeStreamResponse_Status" json:"status,omitempty"`
	// JSON-encoded data to return to a client in a successful
	// subscription result.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStreamResponse) Reset() {
	*x = SubscribeStreamResponse{}
	mi := &file_proto_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStreamResponse) ProtoMessage() {}

func (x *SubscribeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStreamResponse.ProtoReflect.Descriptor instead.
func (*SubscribeStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeStreamResponse) GetStatus() SubscribeStreamResponse_Status {
	if x != nil {
		return x.Status
	}
	return SubscribeStreamResponse_OK
}

func (x *SubscribeStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginContext *PluginContext         `protobuf:"bytes,1,opt,name=plugin_context,json=pluginContext,proto3" json:"plugin_context,omitempty"`
	// path part of a channel.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// data that user wants to publish into a stream
	// (only JSON-encoded at the moment).
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStreamRequest) Reset() {
	*x = PublishStreamRequest{}
	mi := &file_proto_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStreamRequest) ProtoMessage() {}

func (x *PublishStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStreamRequest.ProtoReflect.Descriptor instead.
func (*PublishStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{6}
}

func (x *PublishStreamRequest) GetPluginContext() *PluginContext {
	if x != nil {
		return x.PluginContext
	}
	return nil
}

func (x *PublishStreamRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PublishStreamRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishStreamResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        PublishStreamResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=com.omniview.pluginsdk.PublishStreamResponse_Status" json:"status,omitempty"`
	Data          []byte                       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStreamResponse) Reset() {
	*x = PublishStreamResponse{}
	mi := &file_proto_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStreamResponse) ProtoMessage() {}

func (x *PublishStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStreamResponse.ProtoReflect.Descriptor instead.
func (*PublishStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{7}
}

func (x *PublishStreamResponse) GetStatus() PublishStreamResponse_Status {
	if x != nil {
		return x.Status
	}
	return PublishStreamResponse_OK
}

func (x *PublishStreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RunStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginContext *PluginContext         `protobuf:"bytes,1,opt,name=plugin_context,json=pluginContext,proto3" json:"plugin_context,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStreamRequest) Reset() {
	*x = RunStreamRequest{}
	mi := &file_proto_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStreamRequest) ProtoMessage() {}

func (x *RunStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStreamRequest.ProtoReflect.Descriptor instead.
func (*RunStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{8}
}

func (x *RunStreamRequest) GetPluginContext() *PluginContext {
	if x != nil {
		return x.PluginContext
	}
	return nil
}

func (x *RunStreamRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StreamPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded data to publish into a channel.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacket) Reset() {
	*x = StreamPacket{}
	mi := &file_proto_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacket) ProtoMessage() {}

func (x *StreamPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacket.ProtoReflect.Descriptor instead.
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{9}
}

func (x *StreamPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_command_proto protoreflect.FileDescriptor

const file_proto_command_proto_rawDesc = "" +
	"\n" +
	"\x13proto/command.proto\x12\x16com.omniview.pluginsdk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x02\n" +
	"\rPluginContext\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12b\n" +
	"\x0fplugin_settings\x18\x02 \x03(\v29.com.omniview.pluginsdk.PluginContext.PluginSettingsEntryR\x0epluginSettings\x12b\n" +
	"\x0fglobal_settings\x18\x03 \x03(\v29.com.omniview.pluginsdk.PluginContext.GlobalSettingsEntryR\x0eglobalSettings\x1aA\n" +
	"\x13PluginSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13GlobalSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xe7\x02\n" +
	"\x12CallCommandRequest\x12L\n" +
	"\x0eplugin_context\x18\x01 \x01(\v2%.com.omniview.pluginsdk.PluginContextR\rpluginContext\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12Q\n" +
	"\aheaders\x18\x05 \x03(\v27.com.omniview.pluginsdk.CallCommandRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a^\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".com.omniview.pluginsdk.StringListR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x13CallCommandResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12R\n" +
	"\aheaders\x18\x02 \x03(\v28.com.omniview.pluginsdk.CallCommandResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a^\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".com.omniview.pluginsdk.StringListR\x05value:\x028\x01\"z\n" +
	"\x16SubscribeStreamRequest\x12L\n" +
	"\x0eplugin_context\x18\x01 \x01(\v2%.com.omniview.pluginsdk.PluginContextR\rpluginContext\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb5\x01\n" +
	"\x17SubscribeStreamResponse\x12N\n" +
	"\x06status\x18\x01 \x01(\x0e26.com.omniview.pluginsdk.SubscribeStreamResponse.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"6\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x02\"\x8c\x01\n" +
	"\x14PublishStreamRequest\x12L\n" +
	"\x0eplugin_context\x18\x01 \x01(\v2%.com.omniview.pluginsdk.PluginContextR\rpluginContext\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb1\x01\n" +
	"\x15PublishStreamResponse\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.com.omniview.pluginsdk.PublishStreamResponse.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"6\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x02\"t\n" +
	"\x10RunStreamRequest\x12L\n" +
	"\x0eplugin_context\x18\x01 \x01(\v2%.com.omniview.pluginsdk.PluginContextR\rpluginContext\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\"\n" +
	"\fStreamPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2j\n" +
	"\aCommand\x12_\n" +
	"\x04Call\x12*.com.omniview.pluginsdk.CallCommandRequest\x1a+.com.omniview.pluginsdk.CallCommandResponse2\xb7\x02\n" +
	"\x06Stream\x12l\n" +
	"\tSubscribe\x12..com.omniview.pluginsdk.SubscribeStreamRequest\x1a/.com.omniview.pluginsdk.SubscribeStreamResponse\x12W\n" +
	"\x03Run\x12(.com.omniview.pluginsdk.RunStreamRequest\x1a$.com.omniview.pluginsdk.StreamPacket0\x01\x12f\n" +
	"\aPublish\x12,.com.omniview.pluginsdk.PublishStreamRequest\x1a-.com.omniview.pluginsdk.PublishStreamResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_command_proto_rawDescOnce sync.Once
	file_proto_command_proto_rawDescData []byte
)

func file_proto_command_proto_rawDescGZIP() []byte {
	file_proto_command_proto_rawDescOnce.Do(func() {
		file_proto_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)))
	})
	return file_proto_command_proto_rawDescData
}

var file_proto_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_command_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_command_proto_goTypes = []any{
	(SubscribeStreamResponse_Status)(0), // 0: com.omniview.pluginsdk.SubscribeStreamResponse.Status
	(PublishStreamResponse_Status)(0),   // 1: com.omniview.pluginsdk.PublishStreamResponse.Status
	(*PluginContext)(nil),               // 2: com.omniview.pluginsdk.PluginContext
	(*StringList)(nil),                  // 3: com.omniview.pluginsdk.StringList
	(*CallCommandRequest)(nil),          // 4: com.omniview.pluginsdk.CallCommandRequest
	(*CallCommandResponse)(nil),         // 5: com.omniview.pluginsdk.CallCommandResponse
	(*SubscribeStreamRequest)(nil),      // 6: com.omniview.pluginsdk.SubscribeStreamRequest
	(*SubscribeStreamResponse)(nil),     // 7: com.omniview.pluginsdk.SubscribeStreamResponse
	(*PublishStreamRequest)(nil),        // 8: com.omniview.pluginsdk.PublishStreamRequest
	(*PublishStreamResponse)(nil),       // 9: com.omniview.pluginsdk.PublishStreamResponse
	(*RunStreamRequest)(nil),            // 10: com.omniview.pluginsdk.RunStreamRequest
	(*StreamPacket)(nil),                // 11: com.omniview.pluginsdk.StreamPacket
	nil,                                 // 12: com.omniview.pluginsdk.PluginContext.PluginSettingsEntry
	nil,                                 // 13: com.omniview.pluginsdk.PluginContext.GlobalSettingsEntry
	nil,                                 // 14: com.omniview.pluginsdk.CallCommandRequest.HeadersEntry
	nil,                                 // 15: com.omniview.pluginsdk.CallCommandResponse.HeadersEntry
}
var file_proto_command_proto_depIdxs = []int32{
	12, // 0: com.omniview.pluginsdk.PluginContext.plugin_settings:type_name -> com.omniview.pluginsdk.PluginContext.PluginSettingsEntry
	13, // 1: com.omniview.pluginsdk.PluginContext.global_settings:type_name -> com.omniview.pluginsdk.PluginContext.GlobalSettingsEntry
	2,  // 2: com.omniview.pluginsdk.CallCommandRequest.plugin_context:type_name -> com.omniview.pluginsdk.PluginContext
	14, // 3: com.omniview.pluginsdk.CallCommandRequest.headers:type_name -> com.omniview.pluginsdk.CallCommandRequest.HeadersEntry
	15, // 4: com.omniview.pluginsdk.CallCommandResponse.headers:type_name -> com.omniview.pluginsdk.CallCommandResponse.HeadersEntry
	2,  // 5: com.omniview.pluginsdk.SubscribeStreamRequest.plugin_context:type_name -> com.omniview.pluginsdk.PluginContext
	0,  // 6: com.omniview.pluginsdk.SubscribeStreamResponse.status:type_name -> com.omniview.pluginsdk.SubscribeStreamResponse.Status
	2,  // 7: com.omniview.pluginsdk.PublishStreamRequest.plugin_context:type_name -> com.omniview.pluginsdk.PluginContext
	1,  // 8: com.omniview.pluginsdk.PublishStreamResponse.status:type_name -> com.omniview.pluginsdk.PublishStreamResponse.Status
	2,  // 9: com.omniview.pluginsdk.RunStreamRequest.plugin_context:type_name -> com.omniview.pluginsdk.PluginContext
	3,  // 10: com.omniview.pluginsdk.CallCommandRequest.HeadersEntry.value:type_name -> com.omniview.pluginsdk.StringList
	3,  // 11: com.omniview.pluginsdk.CallCommandResponse.HeadersEntry.value:type_name -> com.omniview.pluginsdk.StringList
	4,  // 12: com.omniview.pluginsdk.Command.Call:input_type -> com.omniview.pluginsdk.CallCommandRequest
	6,  // 13: com.omniview.pluginsdk.Stream.Subscribe:input_type -> com.omniview.pluginsdk.SubscribeStreamRequest
	10, // 14: com.omniview.pluginsdk.Stream.Run:input_type -> com.omniview.pluginsdk.RunStreamRequest
	8,  // 15: com.omniview.pluginsdk.Stream.Publish:input_type -> com.omniview.pluginsdk.PublishStreamRequest
	5,  // 16: com.omniview.pluginsdk.Command.Call:output_type -> com.omniview.pluginsdk.CallCommandResponse
	7,  // 17: com.omniview.pluginsdk.Stream.Subscribe:output_type -> com.omniview.pluginsdk.SubscribeStreamResponse
	11, // 18: com.omniview.pluginsdk.Stream.Run:output_type -> com.omniview.pluginsdk.StreamPacket
	9,  // 19: com.omniview.pluginsdk.Stream.Publish:output_type -> com.omniview.pluginsdk.PublishStreamResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_command_proto_init() }
func file_proto_command_proto_init() {
	if File_proto_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_command_proto_goTypes,
		DependencyIndexes: file_proto_command_proto_depIdxs,
		EnumInfos:         file_proto_command_proto_enumTypes,
		MessageInfos:      file_proto_command_proto_msgTypes,
	}.Build()
	File_proto_command_proto = out.File
	file_proto_command_proto_goTypes = nil
	file_proto_command_proto_depIdxs = nil
}
