// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/logs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LogPlugin_GetSupportedResources_FullMethodName = "/com.omniview.pluginsdk.LogPlugin/GetSupportedResources"
	LogPlugin_CreateSession_FullMethodName         = "/com.omniview.pluginsdk.LogPlugin/CreateSession"
	LogPlugin_GetSession_FullMethodName            = "/com.omniview.pluginsdk.LogPlugin/GetSession"
	LogPlugin_ListSessions_FullMethodName          = "/com.omniview.pluginsdk.LogPlugin/ListSessions"
	LogPlugin_CloseSession_FullMethodName          = "/com.omniview.pluginsdk.LogPlugin/CloseSession"
	LogPlugin_UpdateSessionOptions_FullMethodName  = "/com.omniview.pluginsdk.LogPlugin/UpdateSessionOptions"
	LogPlugin_Stream_FullMethodName                = "/com.omniview.pluginsdk.LogPlugin/Stream"
)

// LogPluginClient is the client API for LogPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogPluginClient interface {
	GetSupportedResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportedLogResourcesResponse, error)
	CreateSession(ctx context.Context, in *CreateLogSessionRequest, opts ...grpc.CallOption) (*CreateLogSessionResponse, error)
	GetSession(ctx context.Context, in *LogSessionByIdRequest, opts ...grpc.CallOption) (*LogSessionByIdResponse, error)
	ListSessions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListLogSessionsResponse, error)
	CloseSession(ctx context.Context, in *LogSessionByIdRequest, opts ...grpc.CallOption) (*CloseLogSessionResponse, error)
	UpdateSessionOptions(ctx context.Context, in *UpdateLogSessionOptionsRequest, opts ...grpc.CallOption) (*LogSessionByIdResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (LogPlugin_StreamClient, error)
}

type logPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewLogPluginClient(cc grpc.ClientConnInterface) LogPluginClient {
	return &logPluginClient{cc}
}

func (c *logPluginClient) GetSupportedResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportedLogResourcesResponse, error) {
	out := new(GetSupportedLogResourcesResponse)
	err := c.cc.Invoke(ctx, LogPlugin_GetSupportedResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) CreateSession(ctx context.Context, in *CreateLogSessionRequest, opts ...grpc.CallOption) (*CreateLogSessionResponse, error) {
	out := new(CreateLogSessionResponse)
	err := c.cc.Invoke(ctx, LogPlugin_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) GetSession(ctx context.Context, in *LogSessionByIdRequest, opts ...grpc.CallOption) (*LogSessionByIdResponse, error) {
	out := new(LogSessionByIdResponse)
	err := c.cc.Invoke(ctx, LogPlugin_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) ListSessions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListLogSessionsResponse, error) {
	out := new(ListLogSessionsResponse)
	err := c.cc.Invoke(ctx, LogPlugin_ListSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) CloseSession(ctx context.Context, in *LogSessionByIdRequest, opts ...grpc.CallOption) (*CloseLogSessionResponse, error) {
	out := new(CloseLogSessionResponse)
	err := c.cc.Invoke(ctx, LogPlugin_CloseSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) UpdateSessionOptions(ctx context.Context, in *UpdateLogSessionOptionsRequest, opts ...grpc.CallOption) (*LogSessionByIdResponse, error) {
	out := new(LogSessionByIdResponse)
	err := c.cc.Invoke(ctx, LogPlugin_UpdateSessionOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logPluginClient) Stream(ctx context.Context, opts ...grpc.CallOption) (LogPlugin_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LogPlugin_ServiceDesc.Streams[0], LogPlugin_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &logPluginStreamClient{stream}
	return x, nil
}

type LogPlugin_StreamClient interface {
	Send(*LogStreamInput) error
	Recv() (*LogStreamOutput, error)
	grpc.ClientStream
}

type logPluginStreamClient struct {
	grpc.ClientStream
}

func (x *logPluginStreamClient) Send(m *LogStreamInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logPluginStreamClient) Recv() (*LogStreamOutput, error) {
	m := new(LogStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogPluginServer is the server API for LogPlugin service.
// All implementations should embed UnimplementedLogPluginServer
// for forward compatibility
type LogPluginServer interface {
	GetSupportedResources(context.Context, *emptypb.Empty) (*GetSupportedLogResourcesResponse, error)
	CreateSession(context.Context, *CreateLogSessionRequest) (*CreateLogSessionResponse, error)
	GetSession(context.Context, *LogSessionByIdRequest) (*LogSessionByIdResponse, error)
	ListSessions(context.Context, *emptypb.Empty) (*ListLogSessionsResponse, error)
	CloseSession(context.Context, *LogSessionByIdRequest) (*CloseLogSessionResponse, error)
	UpdateSessionOptions(context.Context, *UpdateLogSessionOptionsRequest) (*LogSessionByIdResponse, error)
	Stream(LogPlugin_StreamServer) error
}

// UnimplementedLogPluginServer should be embedded to have forward compatible implementations.
type UnimplementedLogPluginServer struct {
}

func (UnimplementedLogPluginServer) GetSupportedResources(context.Context, *emptypb.Empty) (*GetSupportedLogResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedResources not implemented")
}
func (UnimplementedLogPluginServer) CreateSession(context.Context, *CreateLogSessionRequest) (*CreateLogSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedLogPluginServer) GetSession(context.Context, *LogSessionByIdRequest) (*LogSessionByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedLogPluginServer) ListSessions(context.Context, *emptypb.Empty) (*ListLogSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedLogPluginServer) CloseSession(context.Context, *LogSessionByIdRequest) (*CloseLogSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedLogPluginServer) UpdateSessionOptions(context.Context, *UpdateLogSessionOptionsRequest) (*LogSessionByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionOptions not implemented")
}
func (UnimplementedLogPluginServer) Stream(LogPlugin_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

// UnsafeLogPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogPluginServer will
// result in compilation errors.
type UnsafeLogPluginServer interface {
	mustEmbedUnimplementedLogPluginServer()
}

func RegisterLogPluginServer(s grpc.ServiceRegistrar, srv LogPluginServer) {
	s.RegisterService(&LogPlugin_ServiceDesc, srv)
}

func _LogPlugin_GetSupportedResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).GetSupportedResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_GetSupportedResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).GetSupportedResources(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).CreateSession(ctx, req.(*CreateLogSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSessionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).GetSession(ctx, req.(*LogSessionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).ListSessions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogSessionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).CloseSession(ctx, req.(*LogSessionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_UpdateSessionOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLogSessionOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogPluginServer).UpdateSessionOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogPlugin_UpdateSessionOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogPluginServer).UpdateSessionOptions(ctx, req.(*UpdateLogSessionOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogPlugin_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogPluginServer).Stream(&logPluginStreamServer{stream})
}

type LogPlugin_StreamServer interface {
	Send(*LogStreamOutput) error
	Recv() (*LogStreamInput, error)
	grpc.ServerStream
}

type logPluginStreamServer struct {
	grpc.ServerStream
}

func (x *logPluginStreamServer) Send(m *LogStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logPluginStreamServer) Recv() (*LogStreamInput, error) {
	m := new(LogStreamInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogPlugin_ServiceDesc is the grpc.ServiceDesc for LogPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.omniview.pluginsdk.LogPlugin",
	HandlerType: (*LogPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupportedResources",
			Handler:    _LogPlugin_GetSupportedResources_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _LogPlugin_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _LogPlugin_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _LogPlugin_ListSessions_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _LogPlugin_CloseSession_Handler,
		},
		{
			MethodName: "UpdateSessionOptions",
			Handler:    _LogPlugin_UpdateSessionOptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _LogPlugin_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/logs.proto",
}
