// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/logs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLineOrigin int32

const (
	LogLineOrigin_LOG_LINE_ORIGIN_CURRENT  LogLineOrigin = 0
	LogLineOrigin_LOG_LINE_ORIGIN_PREVIOUS LogLineOrigin = 1
	LogLineOrigin_LOG_LINE_ORIGIN_SYSTEM   LogLineOrigin = 2
)

// Enum value maps for LogLineOrigin.
var (
	LogLineOrigin_name = map[int32]string{
		0: "LOG_LINE_ORIGIN_CURRENT",
		1: "LOG_LINE_ORIGIN_PREVIOUS",
		2: "LOG_LINE_ORIGIN_SYSTEM",
	}
	LogLineOrigin_value = map[string]int32{
		"LOG_LINE_ORIGIN_CURRENT":  0,
		"LOG_LINE_ORIGIN_PREVIOUS": 1,
		"LOG_LINE_ORIGIN_SYSTEM":   2,
	}
)

func (x LogLineOrigin) Enum() *LogLineOrigin {
	p := new(LogLineOrigin)
	*p = x
	return p
}

func (x LogLineOrigin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLineOrigin) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[0].Descriptor()
}

func (LogLineOrigin) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[0]
}

func (x LogLineOrigin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLineOrigin.Descriptor instead.
func (LogLineOrigin) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

type LogStreamEventType int32

const (
	LogStreamEventType_LOG_STREAM_EVENT_SOURCE_ADDED   LogStreamEventType = 0
	LogStreamEventType_LOG_STREAM_EVENT_SOURCE_REMOVED LogStreamEventType = 1
	LogStreamEventType_LOG_STREAM_EVENT_STREAM_ERROR   LogStreamEventType = 2
	LogStreamEventType_LOG_STREAM_EVENT_RECONNECTING   LogStreamEventType = 3
	LogStreamEventType_LOG_STREAM_EVENT_RECONNECTED    LogStreamEventType = 4
	LogStreamEventType_LOG_STREAM_EVENT_STREAM_ENDED   LogStreamEventType = 5
)

// Enum value maps for LogStreamEventType.
var (
	LogStreamEventType_name = map[int32]string{
		0: "LOG_STREAM_EVENT_SOURCE_ADDED",
		1: "LOG_STREAM_EVENT_SOURCE_REMOVED",
		2: "LOG_STREAM_EVENT_STREAM_ERROR",
		3: "LOG_STREAM_EVENT_RECONNECTING",
		4: "LOG_STREAM_EVENT_RECONNECTED",
		5: "LOG_STREAM_EVENT_STREAM_ENDED",
	}
	LogStreamEventType_value = map[string]int32{
		"LOG_STREAM_EVENT_SOURCE_ADDED":   0,
		"LOG_STREAM_EVENT_SOURCE_REMOVED": 1,
		"LOG_STREAM_EVENT_STREAM_ERROR":   2,
		"LOG_STREAM_EVENT_RECONNECTING":   3,
		"LOG_STREAM_EVENT_RECONNECTED":    4,
		"LOG_STREAM_EVENT_STREAM_ENDED":   5,
	}
)

func (x LogStreamEventType) Enum() *LogStreamEventType {
	p := new(LogStreamEventType)
	*p = x
	return p
}

func (x LogStreamEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStreamEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[1].Descriptor()
}

func (LogStreamEventType) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[1]
}

func (x LogStreamEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStreamEventType.Descriptor instead.
func (LogStreamEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

type LogStreamCommand int32

const (
	LogStreamCommand_LOG_STREAM_COMMAND_PAUSE  LogStreamCommand = 0
	LogStreamCommand_LOG_STREAM_COMMAND_RESUME LogStreamCommand = 1
	LogStreamCommand_LOG_STREAM_COMMAND_CLOSE  LogStreamCommand = 2
)

// Enum value maps for LogStreamCommand.
var (
	LogStreamCommand_name = map[int32]string{
		0: "LOG_STREAM_COMMAND_PAUSE",
		1: "LOG_STREAM_COMMAND_RESUME",
		2: "LOG_STREAM_COMMAND_CLOSE",
	}
	LogStreamCommand_value = map[string]int32{
		"LOG_STREAM_COMMAND_PAUSE":  0,
		"LOG_STREAM_COMMAND_RESUME": 1,
		"LOG_STREAM_COMMAND_CLOSE":  2,
	}
)

func (x LogStreamCommand) Enum() *LogStreamCommand {
	p := new(LogStreamCommand)
	*p = x
	return p
}

func (x LogStreamCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStreamCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[2].Descriptor()
}

func (LogStreamCommand) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[2]
}

func (x LogStreamCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStreamCommand.Descriptor instead.
func (LogStreamCommand) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2}
}

type LogSessionStatus int32

const (
	LogSessionStatus_LOG_SESSION_STATUS_ACTIVE LogSessionStatus = 0
	LogSessionStatus_LOG_SESSION_STATUS_PAUSED LogSessionStatus = 1
	LogSessionStatus_LOG_SESSION_STATUS_CLOSED LogSessionStatus = 2
	LogSessionStatus_LOG_SESSION_STATUS_ERROR  LogSessionStatus = 3
)

// Enum value maps for LogSessionStatus.
var (
	LogSessionStatus_name = map[int32]string{
		0: "LOG_SESSION_STATUS_ACTIVE",
		1: "LOG_SESSION_STATUS_PAUSED",
		2: "LOG_SESSION_STATUS_CLOSED",
		3: "LOG_SESSION_STATUS_ERROR",
	}
	LogSessionStatus_value = map[string]int32{
		"LOG_SESSION_STATUS_ACTIVE": 0,
		"LOG_SESSION_STATUS_PAUSED": 1,
		"LOG_SESSION_STATUS_CLOSED": 2,
		"LOG_SESSION_STATUS_ERROR":  3,
	}
)

func (x LogSessionStatus) Enum() *LogSessionStatus {
	p := new(LogSessionStatus)
	*p = x
	return p
}

func (x LogSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[3].Descriptor()
}

func (LogSessionStatus) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[3]
}

func (x LogSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSessionStatus.Descriptor instead.
func (LogSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{3}
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Origin        LogLineOrigin          `protobuf:"varint,6,opt,name=origin,proto3,enum=com.omniview.pluginsdk.LogLineOrigin" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_proto_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogLine) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogLine) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *LogLine) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogLine) GetOrigin() LogLineOrigin {
	if x != nil {
		return x.Origin
	}
	return LogLineOrigin_LOG_LINE_ORIGIN_CURRENT
}

type LogSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	mi := &file_proto_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSource.ProtoReflect.Descriptor instead.
func (*LogSource) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogSource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LogStreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LogStreamEventType     `protobuf:"varint,1,opt,name=type,proto3,enum=com.omniview.pluginsdk.LogStreamEventType" json:"type,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamEvent) Reset() {
	*x = LogStreamEvent{}
	mi := &file_proto_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamEvent) ProtoMessage() {}

func (x *LogStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamEvent.ProtoReflect.Descriptor instead.
func (*LogStreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogStreamEvent) GetType() LogStreamEventType {
	if x != nil {
		return x.Type
	}
	return LogStreamEventType_LOG_STREAM_EVENT_SOURCE_ADDED
}

func (x *LogStreamEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *LogStreamEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogStreamEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogSessionOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Target              string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Follow              bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	IncludePrevious     bool                   `protobuf:"varint,3,opt,name=include_previous,json=includePrevious,proto3" json:"include_previous,omitempty"`
	IncludeTimestamps   bool                   `protobuf:"varint,4,opt,name=include_timestamps,json=includeTimestamps,proto3" json:"include_timestamps,omitempty"`
	TailLines           int64                  `protobuf:"varint,5,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	SinceSeconds        int64                  `protobuf:"varint,6,opt,name=since_seconds,json=sinceSeconds,proto3" json:"since_seconds,omitempty"`
	SinceTime           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=since_time,json=sinceTime,proto3" json:"since_time,omitempty"`
	LimitBytes          int64                  `protobuf:"varint,8,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	IncludeSourceEvents bool                   `protobuf:"varint,9,opt,name=include_source_events,json=includeSourceEvents,proto3" json:"include_source_events,omitempty"`
	Params              map[string]string      `protobuf:"bytes,10,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LogSessionOptions) Reset() {
	*x = LogSessionOptions{}
	mi := &file_proto_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSessionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSessionOptions) ProtoMessage() {}

func (x *LogSessionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSessionOptions.ProtoReflect.Descriptor instead.
func (*LogSessionOptions) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogSessionOptions) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LogSessionOptions) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogSessionOptions) GetIncludePrevious() bool {
	if x != nil {
		return x.IncludePrevious
	}
	return false
}

func (x *LogSessionOptions) GetIncludeTimestamps() bool {
	if x != nil {
		return x.IncludeTimestamps
	}
	return false
}

func (x *LogSessionOptions) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *LogSessionOptions) GetSinceSeconds() int64 {
	if x != nil {
		return x.SinceSeconds
	}
	return 0
}

func (x *LogSessionOptions) GetSinceTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceTime
	}
	return nil
}

func (x *LogSessionOptions) GetLimitBytes() int64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *LogSessionOptions) GetIncludeSourceEvents() bool {
	if x != nil {
		return x.IncludeSourceEvents
	}
	return false
}

func (x *LogSessionOptions) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type LogSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ResourceKey   string                 `protobuf:"bytes,4,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Options       *LogSessionOptions     `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	Status        LogSessionStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=com.omniview.pluginsdk.LogSessionStatus" json:"status,omitempty"`
	ActiveSources []*LogSource           `protobuf:"bytes,8,rep,name=active_sources,json=activeSources,proto3" json:"active_sources,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSession) Reset() {
	*x = LogSession{}
	mi := &file_proto_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSession) ProtoMessage() {}

func (x *LogSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSession.ProtoReflect.Descriptor instead.
func (*LogSession) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{4}
}

func (x *LogSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogSession) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *LogSession) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *LogSession) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *LogSession) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *LogSession) GetOptions() *LogSessionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *LogSession) GetStatus() LogSessionStatus {
	if x != nil {
		return x.Status
	}
	return LogSessionStatus_LOG_SESSION_STATUS_ACTIVE
}

func (x *LogSession) GetActiveSources() []*LogSource {
	if x != nil {
		return x.ActiveSources
	}
	return nil
}

func (x *LogSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LogHandler struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Plugin        string                       `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Resource      string                       `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	TargetBuilder *ResourceActionTargetBuilder `protobuf:"bytes,3,opt,name=target_builder,json=targetBuilder,proto3" json:"target_builder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogHandler) Reset() {
	*x = LogHandler{}
	mi := &file_proto_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogHandler) ProtoMessage() {}

func (x *LogHandler) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogHandler.ProtoReflect.Descriptor instead.
func (*LogHandler) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{5}
}

func (x *LogHandler) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *LogHandler) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LogHandler) GetTargetBuilder() *ResourceActionTargetBuilder {
	if x != nil {
		return x.TargetBuilder
	}
	return nil
}

type GetSupportedLogResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handlers      []*LogHandler          `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedLogResourcesResponse) Reset() {
	*x = GetSupportedLogResourcesResponse{}
	mi := &file_proto_logs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedLogResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedLogResourcesResponse) ProtoMessage() {}

func (x *GetSupportedLogResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedLogResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedLogResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{6}
}

func (x *GetSupportedLogResourcesResponse) GetHandlers() []*LogHandler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type CreateLogSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceKey   string                 `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceData  *structpb.Struct       `protobuf:"bytes,3,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	Options       *LogSessionOptions     `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogSessionRequest) Reset() {
	*x = CreateLogSessionRequest{}
	mi := &file_proto_logs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogSessionRequest) ProtoMessage() {}

func (x *CreateLogSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateLogSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLogSessionRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *CreateLogSessionRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateLogSessionRequest) GetResourceData() *structpb.Struct {
	if x != nil {
		return x.ResourceData
	}
	return nil
}

func (x *CreateLogSessionRequest) GetOptions() *LogSessionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateLogSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *LogSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogSessionResponse) Reset() {
	*x = CreateLogSessionResponse{}
	mi := &file_proto_logs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogSessionResponse) ProtoMessage() {}

func (x *CreateLogSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateLogSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLogSessionResponse) GetSession() *LogSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateLogSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLogSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogSessionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSessionByIdRequest) Reset() {
	*x = LogSessionByIdRequest{}
	mi := &file_proto_logs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSessionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSessionByIdRequest) ProtoMessage() {}

func (x *LogSessionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSessionByIdRequest.ProtoReflect.Descriptor instead.
func (*LogSessionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{9}
}

func (x *LogSessionByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LogSessionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *LogSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSessionByIdResponse) Reset() {
	*x = LogSessionByIdResponse{}
	mi := &file_proto_logs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSessionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSessionByIdResponse) ProtoMessage() {}

func (x *LogSessionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSessionByIdResponse.ProtoReflect.Descriptor instead.
func (*LogSessionByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{10}
}

func (x *LogSessionByIdResponse) GetSession() *LogSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LogSessionByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogSessionByIdResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListLogSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*LogSession          `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogSessionsResponse) Reset() {
	*x = ListLogSessionsResponse{}
	mi := &file_proto_logs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogSessionsResponse) ProtoMessage() {}

func (x *ListLogSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListLogSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{11}
}

func (x *ListLogSessionsResponse) GetSessions() []*LogSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListLogSessionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListLogSessionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseLogSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseLogSessionResponse) Reset() {
	*x = CloseLogSessionResponse{}
	mi := &file_proto_logs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseLogSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseLogSessionResponse) ProtoMessage() {}

func (x *CloseLogSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseLogSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseLogSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{12}
}

func (x *CloseLogSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseLogSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateLogSessionOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Options       *LogSessionOptions     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLogSessionOptionsRequest) Reset() {
	*x = UpdateLogSessionOptionsRequest{}
	mi := &file_proto_logs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLogSessionOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLogSessionOptionsRequest) ProtoMessage() {}

func (x *UpdateLogSessionOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLogSessionOptionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLogSessionOptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateLogSessionOptionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateLogSessionOptionsRequest) GetOptions() *LogSessionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type LogStreamInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       LogStreamCommand       `protobuf:"varint,2,opt,name=command,proto3,enum=com.omniview.pluginsdk.LogStreamCommand" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamInput) Reset() {
	*x = LogStreamInput{}
	mi := &file_proto_logs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamInput) ProtoMessage() {}

func (x *LogStreamInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamInput.ProtoReflect.Descriptor instead.
func (*LogStreamInput) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{14}
}

func (x *LogStreamInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogStreamInput) GetCommand() LogStreamCommand {
	if x != nil {
		return x.Command
	}
	return LogStreamCommand_LOG_STREAM_COMMAND_PAUSE
}

type LogStreamOutput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LogStreamOutput_Line
	//	*LogStreamOutput_Event
	Payload       isLogStreamOutput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamOutput) Reset() {
	*x = LogStreamOutput{}
	mi := &file_proto_logs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamOutput) ProtoMessage() {}

func (x *LogStreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamOutput.ProtoReflect.Descriptor instead.
func (*LogStreamOutput) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{15}
}

func (x *LogStreamOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogStreamOutput) GetPayload() isLogStreamOutput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogStreamOutput) GetLine() *LogLine {
	if x != nil {
		if x, ok := x.Payload.(*LogStreamOutput_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *LogStreamOutput) GetEvent() *LogStreamEvent {
	if x != nil {
		if x, ok := x.Payload.(*LogStreamOutput_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isLogStreamOutput_Payload interface {
	isLogStreamOutput_Payload()
}

type LogStreamOutput_Line struct {
	Line *LogLine `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

type LogStreamOutput_Event struct {
	Event *LogStreamEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*LogStreamOutput_Line) isLogStreamOutput_Payload() {}

func (*LogStreamOutput_Event) isLogStreamOutput_Payload() {}

var File_proto_logs_proto protoreflect.FileDescriptor

const file_proto_logs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/logs.proto\x12\x16com.omniview.pluginsdk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14proto/resource.proto\"\xd8\x02\n" +
	"\aLogLine\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12C\n" +
	"\x06labels\x18\x03 \x03(\v2+.com.omniview.pluginsdk.LogLine.LabelsEntryR\x06labels\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12=\n" +
	"\x06origin\x18\x06 \x01(\x0e2%.com.omniview.pluginsdk.LogLineOriginR\x06origin\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\tLogSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x06labels\x18\x02 \x03(\v2-.com.omniview.pluginsdk.LogSource.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0eLogStreamEvent\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.com.omniview.pluginsdk.LogStreamEventTypeR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xfb\x03\n" +
	"\x11LogSessionOptions\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12)\n" +
	"\x10include_previous\x18\x03 \x01(\bR\x0fincludePrevious\x12-\n" +
	"\x12include_timestamps\x18\x04 \x01(\bR\x11includeTimestamps\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x05 \x01(\x03R\ttailLines\x12#\n" +
	"\rsince_seconds\x18\x06 \x01(\x03R\fsinceSeconds\x129\n" +
	"\n" +
	"since_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tsinceTime\x12\x1f\n" +
	"\vlimit_bytes\x18\b \x01(\x03R\n" +
	"limitBytes\x122\n" +
	"\x15include_source_events\x18\t \x01(\bR\x13includeSourceEvents\x12M\n" +
	"\x06params\x18\n" +
	" \x03(\v25.com.omniview.pluginsdk.LogSessionOptions.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x03\n" +
	"\n" +
	"LogSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12!\n" +
	"\fresource_key\x18\x04 \x01(\tR\vresourceKey\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12C\n" +
	"\aoptions\x18\x06 \x01(\v2).com.omniview.pluginsdk.LogSessionOptionsR\aoptions\x12@\n" +
	"\x06status\x18\a \x01(\x0e2(.com.omniview.pluginsdk.LogSessionStatusR\x06status\x12H\n" +
	"\x0eactive_sources\x18\b \x03(\v2!.com.omniview.pluginsdk.LogSourceR\ractiveSources\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9c\x01\n" +
	"\n" +
	"LogHandler\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12Z\n" +
	"\x0etarget_builder\x18\x03 \x01(\v23.com.omniview.pluginsdk.ResourceActionTargetBuilderR\rtargetBuilder\"b\n" +
	" GetSupportedLogResourcesResponse\x12>\n" +
	"\bhandlers\x18\x01 \x03(\v2\".com.omniview.pluginsdk.LogHandlerR\bhandlers\"\xe0\x01\n" +
	"\x17CreateLogSessionRequest\x12!\n" +
	"\fresource_key\x18\x01 \x01(\tR\vresourceKey\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12<\n" +
	"\rresource_data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\fresourceData\x12C\n" +
	"\aoptions\x18\x04 \x01(\v2).com.omniview.pluginsdk.LogSessionOptionsR\aoptions\"\x88\x01\n" +
	"\x18CreateLogSessionResponse\x12<\n" +
	"\asession\x18\x01 \x01(\v2\".com.omniview.pluginsdk.LogSessionR\asession\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"6\n" +
	"\x15LogSessionByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x86\x01\n" +
	"\x16LogSessionByIdResponse\x12<\n" +
	"\asession\x18\x01 \x01(\v2\".com.omniview.pluginsdk.LogSessionR\asession\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x89\x01\n" +
	"\x17ListLogSessionsResponse\x12>\n" +
	"\bsessions\x18\x01 \x03(\v2\".com.omniview.pluginsdk.LogSessionR\bsessions\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"I\n" +
	"\x17CloseLogSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x84\x01\n" +
	"\x1eUpdateLogSessionOptionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12C\n" +
	"\aoptions\x18\x02 \x01(\v2).com.omniview.pluginsdk.LogSessionOptionsR\aoptions\"s\n" +
	"\x0eLogStreamInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12B\n" +
	"\acommand\x18\x02 \x01(\x0e2(.com.omniview.pluginsdk.LogStreamCommandR\acommand\"\xb2\x01\n" +
	"\x0fLogStreamOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\x04line\x18\x02 \x01(\v2\x1f.com.omniview.pluginsdk.LogLineH\x00R\x04line\x12>\n" +
	"\x05event\x18\x03 \x01(\v2&.com.omniview.pluginsdk.LogStreamEventH\x00R\x05eventB\t\n" +
	"\apayload*f\n" +
	"\rLogLineOrigin\x12\x1b\n" +
	"\x17LOG_LINE_ORIGIN_CURRENT\x10\x00\x12\x1c\n" +
	"\x18LOG_LINE_ORIGIN_PREVIOUS\x10\x01\x12\x1a\n" +
	"\x16LOG_LINE_ORIGIN_SYSTEM\x10\x02*\xe7\x01\n" +
	"\x12LogStreamEventType\x12!\n" +
	"\x1dLOG_STREAM_EVENT_SOURCE_ADDED\x10\x00\x12#\n" +
	"\x1fLOG_STREAM_EVENT_SOURCE_REMOVED\x10\x01\x12!\n" +
	"\x1dLOG_STREAM_EVENT_STREAM_ERROR\x10\x02\x12!\n" +
	"\x1dLOG_STREAM_EVENT_RECONNECTING\x10\x03\x12 \n" +
	"\x1cLOG_STREAM_EVENT_RECONNECTED\x10\x04\x12!\n" +
	"\x1dLOG_STREAM_EVENT_STREAM_ENDED\x10\x05*m\n" +
	"\x10LogStreamCommand\x12\x1c\n" +
	"\x18LOG_STREAM_COMMAND_PAUSE\x10\x00\x12\x1d\n" +
	"\x19LOG_STREAM_COMMAND_RESUME\x10\x01\x12\x1c\n" +
	"\x18LOG_STREAM_COMMAND_CLOSE\x10\x02*\x8d\x01\n" +
	"\x10LogSessionStatus\x12\x1d\n" +
	"\x19LOG_SESSION_STATUS_ACTIVE\x10\x00\x12\x1d\n" +
	"\x19LOG_SESSION_STATUS_PAUSED\x10\x01\x12\x1d\n" +
	"\x19LOG_SESSION_STATUS_CLOSED\x10\x02\x12\x1c\n" +
	"\x18LOG_SESSION_STATUS_ERROR\x10\x032\xff\x05\n" +
	"\tLogPlugin\x12i\n" +
	"\x15GetSupportedResources\x12\x16.google.protobuf.Empty\x1a8.com.omniview.pluginsdk.GetSupportedLogResourcesResponse\x12r\n" +
	"\rCreateSession\x12/.com.omniview.pluginsdk.CreateLogSessionRequest\x1a0.com.omniview.pluginsdk.CreateLogSessionResponse\x12k\n" +
	"\n" +
	"GetSession\x12-.com.omniview.pluginsdk.LogSessionByIdRequest\x1a..com.omniview.pluginsdk.LogSessionByIdResponse\x12W\n" +
	"\fListSessions\x12\x16.google.protobuf.Empty\x1a/.com.omniview.pluginsdk.ListLogSessionsResponse\x12n\n" +
	"\fCloseSession\x12-.com.omniview.pluginsdk.LogSessionByIdRequest\x1a/.com.omniview.pluginsdk.CloseLogSessionResponse\x12~\n" +
	"\x14UpdateSessionOptions\x126.com.omniview.pluginsdk.UpdateLogSessionOptionsRequest\x1a..com.omniview.pluginsdk.LogSessionByIdResponse\x12]\n" +
	"\x06Stream\x12&.com.omniview.pluginsdk.LogStreamInput\x1a'.com.omniview.pluginsdk.LogStreamOutput(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_logs_proto_rawDescOnce sync.Once
	file_proto_logs_proto_rawDescData []byte
)

func file_proto_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)))
	})
	return file_proto_logs_proto_rawDescData
}

var file_proto_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_logs_proto_goTypes = []any{
	(LogLineOrigin)(0),                       // 0: com.omniview.pluginsdk.LogLineOrigin
	(LogStreamEventType)(0),                  // 1: com.omniview.pluginsdk.LogStreamEventType
	(LogStreamCommand)(0),                    // 2: com.omniview.pluginsdk.LogStreamCommand
	(LogSessionStatus)(0),                    // 3: com.omniview.pluginsdk.LogSessionStatus
	(*LogLine)(nil),                          // 4: com.omniview.pluginsdk.LogLine
	(*LogSource)(nil),                        // 5: com.omniview.pluginsdk.LogSource
	(*LogStreamEvent)(nil),                   // 6: com.omniview.pluginsdk.LogStreamEvent
	(*LogSessionOptions)(nil),                // 7: com.omniview.pluginsdk.LogSessionOptions
	(*LogSession)(nil),                       // 8: com.omniview.pluginsdk.LogSession
	(*LogHandler)(nil),                       // 9: com.omniview.pluginsdk.LogHandler
	(*GetSupportedLogResourcesResponse)(nil), // 10: com.omniview.pluginsdk.GetSupportedLogResourcesResponse
	(*CreateLogSessionRequest)(nil),          // 11: com.omniview.pluginsdk.CreateLogSessionRequest
	(*CreateLogSessionResponse)(nil),         // 12: com.omniview.pluginsdk.CreateLogSessionResponse
	(*LogSessionByIdRequest)(nil),            // 13: com.omniview.pluginsdk.LogSessionByIdRequest
	(*LogSessionByIdResponse)(nil),           // 14: com.omniview.pluginsdk.LogSessionByIdResponse
	(*ListLogSessionsResponse)(nil),          // 15: com.omniview.pluginsdk.ListLogSessionsResponse
	(*CloseLogSessionResponse)(nil),          // 16: com.omniview.pluginsdk.CloseLogSessionResponse
	(*UpdateLogSessionOptionsRequest)(nil),   // 17: com.omniview.pluginsdk.UpdateLogSessionOptionsRequest
	(*LogStreamInput)(nil),                   // 18: com.omniview.pluginsdk.LogStreamInput
	(*LogStreamOutput)(nil),                  // 19: com.omniview.pluginsdk.LogStreamOutput
	nil,                                      // 20: com.omniview.pluginsdk.LogLine.LabelsEntry
	nil,                                      // 21: com.omniview.pluginsdk.LogSource.LabelsEntry
	nil,                                      // 22: com.omniview.pluginsdk.LogSessionOptions.ParamsEntry
	(*timestamppb.Timestamp)(nil),            // 23: google.protobuf.Timestamp
	(*ResourceActionTargetBuilder)(nil),      // 24: com.omniview.pluginsdk.ResourceActionTargetBuilder
	(*structpb.Struct)(nil),                  // 25: google.protobuf.Struct
	(*emptypb.Empty)(nil),                    // 26: google.protobuf.Empty
}
var file_proto_logs_proto_depIdxs = []int32{
	20, // 0: com.omniview.pluginsdk.LogLine.labels:type_name -> com.omniview.pluginsdk.LogLine.LabelsEntry
	23, // 1: com.omniview.pluginsdk.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: com.omniview.pluginsdk.LogLine.origin:type_name -> com.omniview.pluginsdk.LogLineOrigin
	21, // 3: com.omniview.pluginsdk.LogSource.labels:type_name -> com.omniview.pluginsdk.LogSource.LabelsEntry
	1,  // 4: com.omniview.pluginsdk.LogStreamEvent.type:type_name -> com.omniview.pluginsdk.LogStreamEventType
	23, // 5: com.omniview.pluginsdk.LogStreamEvent.timestamp:type_name -> google.protobuf.Timestamp
	23, // 6: com.omniview.pluginsdk.LogSessionOptions.since_time:type_name -> google.protobuf.Timestamp
	22, // 7: com.omniview.pluginsdk.LogSessionOptions.params:type_name -> com.omniview.pluginsdk.LogSessionOptions.ParamsEntry
	7,  // 8: com.omniview.pluginsdk.LogSession.options:type_name -> com.omniview.pluginsdk.LogSessionOptions
	3,  // 9: com.omniview.pluginsdk.LogSession.status:type_name -> com.omniview.pluginsdk.LogSessionStatus
	5,  // 10: com.omniview.pluginsdk.LogSession.active_sources:type_name -> com.omniview.pluginsdk.LogSource
	23, // 11: com.omniview.pluginsdk.LogSession.created_at:type_name -> google.protobuf.Timestamp
	24, // 12: com.omniview.pluginsdk.LogHandler.target_builder:type_name -> com.omniview.pluginsdk.ResourceActionTargetBuilder
	9,  // 13: com.omniview.pluginsdk.GetSupportedLogResourcesResponse.handlers:type_name -> com.omniview.pluginsdk.LogHandler
	25, // 14: com.omniview.pluginsdk.CreateLogSessionRequest.resource_data:type_name -> google.protobuf.Struct
	7,  // 15: com.omniview.pluginsdk.CreateLogSessionRequest.options:type_name -> com.omniview.pluginsdk.LogSessionOptions
	8,  // 16: com.omniview.pluginsdk.CreateLogSessionResponse.session:type_name -> com.omniview.pluginsdk.LogSession
	8,  // 17: com.omniview.pluginsdk.LogSessionByIdResponse.session:type_name -> com.omniview.pluginsdk.LogSession
	8,  // 18: com.omniview.pluginsdk.ListLogSessionsResponse.sessions:type_name -> com.omniview.pluginsdk.LogSession
	7,  // 19: com.omniview.pluginsdk.UpdateLogSessionOptionsRequest.options:type_name -> com.omniview.pluginsdk.LogSessionOptions
	2,  // 20: com.omniview.pluginsdk.LogStreamInput.command:type_name -> com.omniview.pluginsdk.LogStreamCommand
	4,  // 21: com.omniview.pluginsdk.LogStreamOutput.line:type_name -> com.omniview.pluginsdk.LogLine
	6,  // 22: com.omniview.pluginsdk.LogStreamOutput.event:type_name -> com.omniview.pluginsdk.LogStreamEvent
	26, // 23: com.omniview.pluginsdk.LogPlugin.GetSupportedResources:input_type -> google.protobuf.Empty
	11, // 24: com.omniview.pluginsdk.LogPlugin.CreateSession:input_type -> com.omniview.pluginsdk.CreateLogSessionRequest
	13, // 25: com.omniview.pluginsdk.LogPlugin.GetSession:input_type -> com.omniview.pluginsdk.LogSessionByIdRequest
	26, // 26: com.omniview.pluginsdk.LogPlugin.ListSessions:input_type -> google.protobuf.Empty
	13, // 27: com.omniview.pluginsdk.LogPlugin.CloseSession:input_type -> com.omniview.pluginsdk.LogSessionByIdRequest
	17, // 28: com.omniview.pluginsdk.LogPlugin.UpdateSessionOptions:input_type -> com.omniview.pluginsdk.UpdateLogSessionOptionsRequest
	18, // 29: com.omniview.pluginsdk.LogPlugin.Stream:input_type -> com.omniview.pluginsdk.LogStreamInput
	10, // 30: com.omniview.pluginsdk.LogPlugin.GetSupportedResources:output_type -> com.omniview.pluginsdk.GetSupportedLogResourcesResponse
	12, // 31: com.omniview.pluginsdk.LogPlugin.CreateSession:output_type -> com.omniview.pluginsdk.CreateLogSessionResponse
	14, // 32: com.omniview.pluginsdk.LogPlugin.GetSession:output_type -> com.omniview.pluginsdk.LogSessionByIdResponse
	15, // 33: com.omniview.pluginsdk.LogPlugin.ListSessions:output_type -> com.omniview.pluginsdk.ListLogSessionsResponse
	16, // 34: com.omniview.pluginsdk.LogPlugin.CloseSession:output_type -> com.omniview.pluginsdk.CloseLogSessionResponse
	14, // 35: com.omniview.pluginsdk.LogPlugin.UpdateSessionOptions:output_type -> com.omniview.pluginsdk.LogSessionByIdResponse
	19, // 36: com.omniview.pluginsdk.LogPlugin.Stream:output_type -> com.omniview.pluginsdk.LogStreamOutput
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_logs_proto_init() }
func file_proto_logs_proto_init() {
	if File_proto_logs_proto != nil {
		return
	}
	file_proto_resource_proto_init()
	file_proto_logs_proto_msgTypes[15].OneofWrappers = []any{
		(*LogStreamOutput_Line)(nil),
		(*LogStreamOutput_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_proto_depIdxs,
		EnumInfos:         file_proto_logs_proto_enumTypes,
		MessageInfos:      file_proto_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_proto = out.File
	file_proto_logs_proto_goTypes = nil
	file_proto_logs_proto_depIdxs = nil
}
