// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/metric.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MetricPlugin_GetSupportedResources_FullMethodName = "/com.omniview.pluginsdk.MetricPlugin/GetSupportedResources"
	MetricPlugin_Query_FullMethodName                 = "/com.omniview.pluginsdk.MetricPlugin/Query"
	MetricPlugin_StreamMetrics_FullMethodName         = "/com.omniview.pluginsdk.MetricPlugin/StreamMetrics"
)

// MetricPluginClient is the client API for MetricPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricPluginClient interface {
	GetSupportedResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportedMetricResourcesResponse, error)
	Query(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MetricPlugin_StreamMetricsClient, error)
}

type metricPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricPluginClient(cc grpc.ClientConnInterface) MetricPluginClient {
	return &metricPluginClient{cc}
}

func (c *metricPluginClient) GetSupportedResources(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSupportedMetricResourcesResponse, error) {
	out := new(GetSupportedMetricResourcesResponse)
	err := c.cc.Invoke(ctx, MetricPlugin_GetSupportedResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricPluginClient) Query(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, MetricPlugin_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricPluginClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MetricPlugin_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MetricPlugin_ServiceDesc.Streams[0], MetricPlugin_StreamMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &metricPluginStreamMetricsClient{stream}
	return x, nil
}

type MetricPlugin_StreamMetricsClient interface {
	Send(*MetricStreamInput) error
	Recv() (*MetricStreamOutput, error)
	grpc.ClientStream
}

type metricPluginStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *metricPluginStreamMetricsClient) Send(m *MetricStreamInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricPluginStreamMetricsClient) Recv() (*MetricStreamOutput, error) {
	m := new(MetricStreamOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricPluginServer is the server API for MetricPlugin service.
// All implementations should embed UnimplementedMetricPluginServer
// for forward compatibility
type MetricPluginServer interface {
	GetSupportedResources(context.Context, *emptypb.Empty) (*GetSupportedMetricResourcesResponse, error)
	Query(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	StreamMetrics(MetricPlugin_StreamMetricsServer) error
}

// UnimplementedMetricPluginServer should be embedded to have forward compatible implementations.
type UnimplementedMetricPluginServer struct {
}

func (UnimplementedMetricPluginServer) GetSupportedResources(context.Context, *emptypb.Empty) (*GetSupportedMetricResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportedResources not implemented")
}
func (UnimplementedMetricPluginServer) Query(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedMetricPluginServer) StreamMetrics(MetricPlugin_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}

// UnsafeMetricPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricPluginServer will
// result in compilation errors.
type UnsafeMetricPluginServer interface {
	mustEmbedUnimplementedMetricPluginServer()
}

func RegisterMetricPluginServer(s grpc.ServiceRegistrar, srv MetricPluginServer) {
	s.RegisterService(&MetricPlugin_ServiceDesc, srv)
}

func _MetricPlugin_GetSupportedResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricPluginServer).GetSupportedResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricPlugin_GetSupportedResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricPluginServer).GetSupportedResources(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricPlugin_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricPluginServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricPlugin_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricPluginServer).Query(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricPlugin_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricPluginServer).StreamMetrics(&metricPluginStreamMetricsServer{stream})
}

type MetricPlugin_StreamMetricsServer interface {
	Send(*MetricStreamOutput) error
	Recv() (*MetricStreamInput, error)
	grpc.ServerStream
}

type metricPluginStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *metricPluginStreamMetricsServer) Send(m *MetricStreamOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricPluginStreamMetricsServer) Recv() (*MetricStreamInput, error) {
	m := new(MetricStreamInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricPlugin_ServiceDesc is the grpc.ServiceDesc for MetricPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.omniview.pluginsdk.MetricPlugin",
	HandlerType: (*MetricPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupportedResources",
			Handler:    _MetricPlugin_GetSupportedResources_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _MetricPlugin_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MetricPlugin_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/metric.proto",
}
