// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/metric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricUnit int32

const (
	MetricUnit_METRIC_UNIT_NONE          MetricUnit = 0
	MetricUnit_METRIC_UNIT_BYTES         MetricUnit = 1
	MetricUnit_METRIC_UNIT_KB            MetricUnit = 2
	MetricUnit_METRIC_UNIT_MB            MetricUnit = 3
	MetricUnit_METRIC_UNIT_GB            MetricUnit = 4
	MetricUnit_METRIC_UNIT_PERCENTAGE    MetricUnit = 5
	MetricUnit_METRIC_UNIT_MILLISECONDS  MetricUnit = 6
	MetricUnit_METRIC_UNIT_SECONDS       MetricUnit = 7
	MetricUnit_METRIC_UNIT_COUNT         MetricUnit = 8
	MetricUnit_METRIC_UNIT_OPS_PER_SEC   MetricUnit = 9
	MetricUnit_METRIC_UNIT_BYTES_PER_SEC MetricUnit = 10
	MetricUnit_METRIC_UNIT_MILLICORES    MetricUnit = 11
	MetricUnit_METRIC_UNIT_CORES         MetricUnit = 12
)

// Enum value maps for MetricUnit.
var (
	MetricUnit_name = map[int32]string{
		0:  "METRIC_UNIT_NONE",
		1:  "METRIC_UNIT_BYTES",
		2:  "METRIC_UNIT_KB",
		3:  "METRIC_UNIT_MB",
		4:  "METRIC_UNIT_GB",
		5:  "METRIC_UNIT_PERCENTAGE",
		6:  "METRIC_UNIT_MILLISECONDS",
		7:  "METRIC_UNIT_SECONDS",
		8:  "METRIC_UNIT_COUNT",
		9:  "METRIC_UNIT_OPS_PER_SEC",
		10: "METRIC_UNIT_BYTES_PER_SEC",
		11: "METRIC_UNIT_MILLICORES",
		12: "METRIC_UNIT_CORES",
	}
	MetricUnit_value = map[string]int32{
		"METRIC_UNIT_NONE":          0,
		"METRIC_UNIT_BYTES":         1,
		"METRIC_UNIT_KB":            2,
		"METRIC_UNIT_MB":            3,
		"METRIC_UNIT_GB":            4,
		"METRIC_UNIT_PERCENTAGE":    5,
		"METRIC_UNIT_MILLISECONDS":  6,
		"METRIC_UNIT_SECONDS":       7,
		"METRIC_UNIT_COUNT":         8,
		"METRIC_UNIT_OPS_PER_SEC":   9,
		"METRIC_UNIT_BYTES_PER_SEC": 10,
		"METRIC_UNIT_MILLICORES":    11,
		"METRIC_UNIT_CORES":         12,
	}
)

func (x MetricUnit) Enum() *MetricUnit {
	p := new(MetricUnit)
	*p = x
	return p
}

func (x MetricUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metric_proto_enumTypes[0].Descriptor()
}

func (MetricUnit) Type() protoreflect.EnumType {
	return &file_proto_metric_proto_enumTypes[0]
}

func (x MetricUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricUnit.Descriptor instead.
func (MetricUnit) EnumDescriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{0}
}

type MetricShape int32

const (
	MetricShape_METRIC_SHAPE_CURRENT    MetricShape = 0
	MetricShape_METRIC_SHAPE_TIMESERIES MetricShape = 1
	MetricShape_METRIC_SHAPE_AGGREGATE  MetricShape = 2
)

// Enum value maps for MetricShape.
var (
	MetricShape_name = map[int32]string{
		0: "METRIC_SHAPE_CURRENT",
		1: "METRIC_SHAPE_TIMESERIES",
		2: "METRIC_SHAPE_AGGREGATE",
	}
	MetricShape_value = map[string]int32{
		"METRIC_SHAPE_CURRENT":    0,
		"METRIC_SHAPE_TIMESERIES": 1,
		"METRIC_SHAPE_AGGREGATE":  2,
	}
)

func (x MetricShape) Enum() *MetricShape {
	p := new(MetricShape)
	*p = x
	return p
}

func (x MetricShape) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricShape) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metric_proto_enumTypes[1].Descriptor()
}

func (MetricShape) Type() protoreflect.EnumType {
	return &file_proto_metric_proto_enumTypes[1]
}

func (x MetricShape) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricShape.Descriptor instead.
func (MetricShape) EnumDescriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{1}
}

type MetricStreamCommand int32

const (
	MetricStreamCommand_METRIC_STREAM_COMMAND_SUBSCRIBE   MetricStreamCommand = 0
	MetricStreamCommand_METRIC_STREAM_COMMAND_UNSUBSCRIBE MetricStreamCommand = 1
	MetricStreamCommand_METRIC_STREAM_COMMAND_CLOSE       MetricStreamCommand = 2
)

// Enum value maps for MetricStreamCommand.
var (
	MetricStreamCommand_name = map[int32]string{
		0: "METRIC_STREAM_COMMAND_SUBSCRIBE",
		1: "METRIC_STREAM_COMMAND_UNSUBSCRIBE",
		2: "METRIC_STREAM_COMMAND_CLOSE",
	}
	MetricStreamCommand_value = map[string]int32{
		"METRIC_STREAM_COMMAND_SUBSCRIBE":   0,
		"METRIC_STREAM_COMMAND_UNSUBSCRIBE": 1,
		"METRIC_STREAM_COMMAND_CLOSE":       2,
	}
)

func (x MetricStreamCommand) Enum() *MetricStreamCommand {
	p := new(MetricStreamCommand)
	*p = x
	return p
}

func (x MetricStreamCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricStreamCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metric_proto_enumTypes[2].Descriptor()
}

func (MetricStreamCommand) Type() protoreflect.EnumType {
	return &file_proto_metric_proto_enumTypes[2]
}

func (x MetricStreamCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricStreamCommand.Descriptor instead.
func (MetricStreamCommand) EnumDescriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{2}
}

type MetricProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricProviderInfo) Reset() {
	*x = MetricProviderInfo{}
	mi := &file_proto_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricProviderInfo) ProtoMessage() {}

func (x *MetricProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricProviderInfo.ProtoReflect.Descriptor instead.
func (*MetricProviderInfo) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{0}
}

func (x *MetricProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricProviderInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MetricProviderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MetricColorRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricColorRange) Reset() {
	*x = MetricColorRange{}
	mi := &file_proto_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricColorRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricColorRange) ProtoMessage() {}

func (x *MetricColorRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricColorRange.ProtoReflect.Descriptor instead.
func (*MetricColorRange) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{1}
}

func (x *MetricColorRange) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MetricColorRange) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *MetricColorRange) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type MetricDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit            MetricUnit             `protobuf:"varint,3,opt,name=unit,proto3,enum=com.omniview.pluginsdk.MetricUnit" json:"unit,omitempty"`
	Icon            string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	ColorRanges     []*MetricColorRange    `protobuf:"bytes,5,rep,name=color_ranges,json=colorRanges,proto3" json:"color_ranges,omitempty"`
	FormatString    string                 `protobuf:"bytes,6,opt,name=format_string,json=formatString,proto3" json:"format_string,omitempty"`
	SupportedShapes []MetricShape          `protobuf:"varint,7,rep,packed,name=supported_shapes,json=supportedShapes,proto3,enum=com.omniview.pluginsdk.MetricShape" json:"supported_shapes,omitempty"`
	ChartGroup      string                 `protobuf:"bytes,8,opt,name=chart_group,json=chartGroup,proto3" json:"chart_group,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricDescriptor) Reset() {
	*x = MetricDescriptor{}
	mi := &file_proto_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDescriptor) ProtoMessage() {}

func (x *MetricDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDescriptor.ProtoReflect.Descriptor instead.
func (*MetricDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{2}
}

func (x *MetricDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDescriptor) GetUnit() MetricUnit {
	if x != nil {
		return x.Unit
	}
	return MetricUnit_METRIC_UNIT_NONE
}

func (x *MetricDescriptor) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MetricDescriptor) GetColorRanges() []*MetricColorRange {
	if x != nil {
		return x.ColorRanges
	}
	return nil
}

func (x *MetricDescriptor) GetFormatString() string {
	if x != nil {
		return x.FormatString
	}
	return ""
}

func (x *MetricDescriptor) GetSupportedShapes() []MetricShape {
	if x != nil {
		return x.SupportedShapes
	}
	return nil
}

func (x *MetricDescriptor) GetChartGroup() string {
	if x != nil {
		return x.ChartGroup
	}
	return ""
}

type MetricHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Metrics       []*MetricDescriptor    `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricHandler) Reset() {
	*x = MetricHandler{}
	mi := &file_proto_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricHandler) ProtoMessage() {}

func (x *MetricHandler) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricHandler.ProtoReflect.Descriptor instead.
func (*MetricHandler) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{3}
}

func (x *MetricHandler) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MetricHandler) GetMetrics() []*MetricDescriptor {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_proto_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{4}
}

func (x *DataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TimeSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricId      string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	DataPoints    []*DataPoint           `protobuf:"bytes,2,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSeries) Reset() {
	*x = TimeSeries{}
	mi := &file_proto_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeries) ProtoMessage() {}

func (x *TimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeries.ProtoReflect.Descriptor instead.
func (*TimeSeries) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{5}
}

func (x *TimeSeries) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *TimeSeries) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *TimeSeries) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CurrentValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricId      string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentValue) Reset() {
	*x = CurrentValue{}
	mi := &file_proto_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentValue) ProtoMessage() {}

func (x *CurrentValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentValue.ProtoReflect.Descriptor instead.
func (*CurrentValue) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{6}
}

func (x *CurrentValue) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *CurrentValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CurrentValue) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CurrentValue) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AggregateValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricId      string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Min           float64                `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	Avg           float64                `protobuf:"fixed64,4,opt,name=avg,proto3" json:"avg,omitempty"`
	Sum           float64                `protobuf:"fixed64,5,opt,name=sum,proto3" json:"sum,omitempty"`
	P50           float64                `protobuf:"fixed64,6,opt,name=p50,proto3" json:"p50,omitempty"`
	P90           float64                `protobuf:"fixed64,7,opt,name=p90,proto3" json:"p90,omitempty"`
	P99           float64                `protobuf:"fixed64,8,opt,name=p99,proto3" json:"p99,omitempty"`
	Count         int64                  `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,10,opt,name=window,proto3" json:"window,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateValue) Reset() {
	*x = AggregateValue{}
	mi := &file_proto_metric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateValue) ProtoMessage() {}

func (x *AggregateValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateValue.ProtoReflect.Descriptor instead.
func (*AggregateValue) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{7}
}

func (x *AggregateValue) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *AggregateValue) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AggregateValue) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AggregateValue) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *AggregateValue) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *AggregateValue) GetP50() float64 {
	if x != nil {
		return x.P50
	}
	return 0
}

func (x *AggregateValue) GetP90() float64 {
	if x != nil {
		return x.P90
	}
	return 0
}

func (x *AggregateValue) GetP99() float64 {
	if x != nil {
		return x.P99
	}
	return 0
}

func (x *AggregateValue) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AggregateValue) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *AggregateValue) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*MetricResult_TimeSeries
	//	*MetricResult_CurrentValue
	//	*MetricResult_AggregateValue
	Result        isMetricResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResult) Reset() {
	*x = MetricResult{}
	mi := &file_proto_metric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResult) ProtoMessage() {}

func (x *MetricResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResult.ProtoReflect.Descriptor instead.
func (*MetricResult) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{8}
}

func (x *MetricResult) GetResult() isMetricResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MetricResult) GetTimeSeries() *TimeSeries {
	if x != nil {
		if x, ok := x.Result.(*MetricResult_TimeSeries); ok {
			return x.TimeSeries
		}
	}
	return nil
}

func (x *MetricResult) GetCurrentValue() *CurrentValue {
	if x != nil {
		if x, ok := x.Result.(*MetricResult_CurrentValue); ok {
			return x.CurrentValue
		}
	}
	return nil
}

func (x *MetricResult) GetAggregateValue() *AggregateValue {
	if x != nil {
		if x, ok := x.Result.(*MetricResult_AggregateValue); ok {
			return x.AggregateValue
		}
	}
	return nil
}

type isMetricResult_Result interface {
	isMetricResult_Result()
}

type MetricResult_TimeSeries struct {
	TimeSeries *TimeSeries `protobuf:"bytes,1,opt,name=time_series,json=timeSeries,proto3,oneof"`
}

type MetricResult_CurrentValue struct {
	CurrentValue *CurrentValue `protobuf:"bytes,2,opt,name=current_value,json=currentValue,proto3,oneof"`
}

type MetricResult_AggregateValue struct {
	AggregateValue *AggregateValue `protobuf:"bytes,3,opt,name=aggregate_value,json=aggregateValue,proto3,oneof"`
}

func (*MetricResult_TimeSeries) isMetricResult_Result() {}

func (*MetricResult_CurrentValue) isMetricResult_Result() {}

func (*MetricResult_AggregateValue) isMetricResult_Result() {}

type GetSupportedMetricResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *MetricProviderInfo    `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Handlers      []*MetricHandler       `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedMetricResourcesResponse) Reset() {
	*x = GetSupportedMetricResourcesResponse{}
	mi := &file_proto_metric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedMetricResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedMetricResourcesResponse) ProtoMessage() {}

func (x *GetSupportedMetricResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedMetricResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedMetricResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{9}
}

func (x *GetSupportedMetricResourcesResponse) GetProvider() *MetricProviderInfo {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetSupportedMetricResourcesResponse) GetHandlers() []*MetricHandler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type QueryMetricsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResourceKey       string                 `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	ResourceId        string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceNamespace string                 `protobuf:"bytes,3,opt,name=resource_namespace,json=resourceNamespace,proto3" json:"resource_namespace,omitempty"`
	ResourceData      *structpb.Struct       `protobuf:"bytes,4,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	MetricIds         []string               `protobuf:"bytes,5,rep,name=metric_ids,json=metricIds,proto3" json:"metric_ids,omitempty"`
	Shape             MetricShape            `protobuf:"varint,6,opt,name=shape,proto3,enum=com.omniview.pluginsdk.MetricShape" json:"shape,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Step              *durationpb.Duration   `protobuf:"bytes,9,opt,name=step,proto3" json:"step,omitempty"`
	Params            map[string]string      `protobuf:"bytes,10,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_proto_metric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{10}
}

func (x *QueryMetricsRequest) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *QueryMetricsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *QueryMetricsRequest) GetResourceNamespace() string {
	if x != nil {
		return x.ResourceNamespace
	}
	return ""
}

func (x *QueryMetricsRequest) GetResourceData() *structpb.Struct {
	if x != nil {
		return x.ResourceData
	}
	return nil
}

func (x *QueryMetricsRequest) GetMetricIds() []string {
	if x != nil {
		return x.MetricIds
	}
	return nil
}

func (x *QueryMetricsRequest) GetShape() MetricShape {
	if x != nil {
		return x.Shape
	}
	return MetricShape_METRIC_SHAPE_CURRENT
}

func (x *QueryMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryMetricsRequest) GetStep() *durationpb.Duration {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *QueryMetricsRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Results       []*MetricResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_proto_metric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{11}
}

func (x *QueryMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryMetricsResponse) GetResults() []*MetricResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MetricStreamInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId    string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Command           MetricStreamCommand    `protobuf:"varint,2,opt,name=command,proto3,enum=com.omniview.pluginsdk.MetricStreamCommand" json:"command,omitempty"`
	ResourceKey       string                 `protobuf:"bytes,3,opt,name=resource_key,json=resourceKey,proto3" json:"resource_key,omitempty"`
	ResourceId        string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceNamespace string                 `protobuf:"bytes,5,opt,name=resource_namespace,json=resourceNamespace,proto3" json:"resource_namespace,omitempty"`
	ResourceData      *structpb.Struct       `protobuf:"bytes,6,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	MetricIds         []string               `protobuf:"bytes,7,rep,name=metric_ids,json=metricIds,proto3" json:"metric_ids,omitempty"`
	Interval          *durationpb.Duration   `protobuf:"bytes,8,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricStreamInput) Reset() {
	*x = MetricStreamInput{}
	mi := &file_proto_metric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStreamInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStreamInput) ProtoMessage() {}

func (x *MetricStreamInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStreamInput.ProtoReflect.Descriptor instead.
func (*MetricStreamInput) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{12}
}

func (x *MetricStreamInput) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *MetricStreamInput) GetCommand() MetricStreamCommand {
	if x != nil {
		return x.Command
	}
	return MetricStreamCommand_METRIC_STREAM_COMMAND_SUBSCRIBE
}

func (x *MetricStreamInput) GetResourceKey() string {
	if x != nil {
		return x.ResourceKey
	}
	return ""
}

func (x *MetricStreamInput) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *MetricStreamInput) GetResourceNamespace() string {
	if x != nil {
		return x.ResourceNamespace
	}
	return ""
}

func (x *MetricStreamInput) GetResourceData() *structpb.Struct {
	if x != nil {
		return x.ResourceData
	}
	return nil
}

func (x *MetricStreamInput) GetMetricIds() []string {
	if x != nil {
		return x.MetricIds
	}
	return nil
}

func (x *MetricStreamInput) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type MetricStreamOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Results        []*MetricResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricStreamOutput) Reset() {
	*x = MetricStreamOutput{}
	mi := &file_proto_metric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStreamOutput) ProtoMessage() {}

func (x *MetricStreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStreamOutput.ProtoReflect.Descriptor instead.
func (*MetricStreamOutput) Descriptor() ([]byte, []int) {
	return file_proto_metric_proto_rawDescGZIP(), []int{13}
}

func (x *MetricStreamOutput) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *MetricStreamOutput) GetResults() []*MetricResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *MetricStreamOutput) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricStreamOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_metric_proto protoreflect.FileDescriptor

const file_proto_metric_proto_rawDesc = "" +
	"\n" +
	"\x12proto/metric.proto\x12\x16com.omniview.pluginsdk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"n\n" +
	"\x12MetricProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"L\n" +
	"\x10MetricColorRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"\xe5\x02\n" +
	"\x10MetricDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x04unit\x18\x03 \x01(\x0e2\".com.omniview.pluginsdk.MetricUnitR\x04unit\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12K\n" +
	"\fcolor_ranges\x18\x05 \x03(\v2(.com.omniview.pluginsdk.MetricColorRangeR\vcolorRanges\x12#\n" +
	"\rformat_string\x18\x06 \x01(\tR\fformatString\x12N\n" +
	"\x10supported_shapes\x18\a \x03(\x0e2#.com.omniview.pluginsdk.MetricShapeR\x0fsupportedShapes\x12\x1f\n" +
	"\vchart_group\x18\b \x01(\tR\n" +
	"chartGroup\"o\n" +
	"\rMetricHandler\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12B\n" +
	"\ametrics\x18\x02 \x03(\v2(.com.omniview.pluginsdk.MetricDescriptorR\ametrics\"\xdd\x01\n" +
	"\tDataPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12E\n" +
	"\x06labels\x18\x03 \x03(\v2-.com.omniview.pluginsdk.DataPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\n" +
	"TimeSeries\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12B\n" +
	"\vdata_points\x18\x02 \x03(\v2!.com.omniview.pluginsdk.DataPointR\n" +
	"dataPoints\x12F\n" +
	"\x06labels\x18\x03 \x03(\v2..com.omniview.pluginsdk.TimeSeries.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\fCurrentValue\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12H\n" +
	"\x06labels\x18\x04 \x03(\v20.com.omniview.pluginsdk.CurrentValue.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x02\n" +
	"\x0eAggregateValue\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\x12\x10\n" +
	"\x03avg\x18\x04 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03sum\x18\x05 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03p50\x18\x06 \x01(\x01R\x03p50\x12\x10\n" +
	"\x03p90\x18\a \x01(\x01R\x03p90\x12\x10\n" +
	"\x03p99\x18\b \x01(\x01R\x03p99\x12\x14\n" +
	"\x05count\x18\t \x01(\x03R\x05count\x121\n" +
	"\x06window\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x06window\x12J\n" +
	"\x06labels\x18\v \x03(\v22.com.omniview.pluginsdk.AggregateValue.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\fMetricResult\x12E\n" +
	"\vtime_series\x18\x01 \x01(\v2\".com.omniview.pluginsdk.TimeSeriesH\x00R\n" +
	"timeSeries\x12K\n" +
	"\rcurrent_value\x18\x02 \x01(\v2$.com.omniview.pluginsdk.CurrentValueH\x00R\fcurrentValue\x12Q\n" +
	"\x0faggregate_value\x18\x03 \x01(\v2&.com.omniview.pluginsdk.AggregateValueH\x00R\x0eaggregateValueB\b\n" +
	"\x06result\"\xb0\x01\n" +
	"#GetSupportedMetricResourcesResponse\x12F\n" +
	"\bprovider\x18\x01 \x01(\v2*.com.omniview.pluginsdk.MetricProviderInfoR\bprovider\x12A\n" +
	"\bhandlers\x18\x02 \x03(\v2%.com.omniview.pluginsdk.MetricHandlerR\bhandlers\"\xcd\x04\n" +
	"\x13QueryMetricsRequest\x12!\n" +
	"\fresource_key\x18\x01 \x01(\tR\vresourceKey\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12-\n" +
	"\x12resource_namespace\x18\x03 \x01(\tR\x11resourceNamespace\x12<\n" +
	"\rresource_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\fresourceData\x12\x1d\n" +
	"\n" +
	"metric_ids\x18\x05 \x03(\tR\tmetricIds\x129\n" +
	"\x05shape\x18\x06 \x01(\x0e2#.com.omniview.pluginsdk.MetricShapeR\x05shape\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12-\n" +
	"\x04step\x18\t \x01(\v2\x19.google.protobuf.DurationR\x04step\x12O\n" +
	"\x06params\x18\n" +
	" \x03(\v27.com.omniview.pluginsdk.QueryMetricsRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x14QueryMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.com.omniview.pluginsdk.MetricResultR\aresults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8a\x03\n" +
	"\x11MetricStreamInput\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12E\n" +
	"\acommand\x18\x02 \x01(\x0e2+.com.omniview.pluginsdk.MetricStreamCommandR\acommand\x12!\n" +
	"\fresource_key\x18\x03 \x01(\tR\vresourceKey\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12-\n" +
	"\x12resource_namespace\x18\x05 \x01(\tR\x11resourceNamespace\x12<\n" +
	"\rresource_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\fresourceData\x12\x1d\n" +
	"\n" +
	"metric_ids\x18\a \x03(\tR\tmetricIds\x125\n" +
	"\binterval\x18\b \x01(\v2\x19.google.protobuf.DurationR\binterval\"\xcd\x01\n" +
	"\x12MetricStreamOutput\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12>\n" +
	"\aresults\x18\x02 \x03(\v2$.com.omniview.pluginsdk.MetricResultR\aresults\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\xce\x02\n" +
	"\n" +
	"MetricUnit\x12\x14\n" +
	"\x10METRIC_UNIT_NONE\x10\x00\x12\x15\n" +
	"\x11METRIC_UNIT_BYTES\x10\x01\x12\x12\n" +
	"\x0eMETRIC_UNIT_KB\x10\x02\x12\x12\n" +
	"\x0eMETRIC_UNIT_MB\x10\x03\x12\x12\n" +
	"\x0eMETRIC_UNIT_GB\x10\x04\x12\x1a\n" +
	"\x16METRIC_UNIT_PERCENTAGE\x10\x05\x12\x1c\n" +
	"\x18METRIC_UNIT_MILLISECONDS\x10\x06\x12\x17\n" +
	"\x13METRIC_UNIT_SECONDS\x10\a\x12\x15\n" +
	"\x11METRIC_UNIT_COUNT\x10\b\x12\x1b\n" +
	"\x17METRIC_UNIT_OPS_PER_SEC\x10\t\x12\x1d\n" +
	"\x19METRIC_UNIT_BYTES_PER_SEC\x10\n" +
	"\x12\x1a\n" +
	"\x16METRIC_UNIT_MILLICORES\x10\v\x12\x15\n" +
	"\x11METRIC_UNIT_CORES\x10\f*`\n" +
	"\vMetricShape\x12\x18\n" +
	"\x14METRIC_SHAPE_CURRENT\x10\x00\x12\x1b\n" +
	"\x17METRIC_SHAPE_TIMESERIES\x10\x01\x12\x1a\n" +
	"\x16METRIC_SHAPE_AGGREGATE\x10\x02*\x82\x01\n" +
	"\x13MetricStreamCommand\x12#\n" +
	"\x1fMETRIC_STREAM_COMMAND_SUBSCRIBE\x10\x00\x12%\n" +
	"!METRIC_STREAM_COMMAND_UNSUBSCRIBE\x10\x01\x12\x1f\n" +
	"\x1bMETRIC_STREAM_COMMAND_CLOSE\x10\x022\xcc\x02\n" +
	"\fMetricPlugin\x12l\n" +
	"\x15GetSupportedResources\x12\x16.google.protobuf.Empty\x1a;.com.omniview.pluginsdk.GetSupportedMetricResourcesResponse\x12b\n" +
	"\x05Query\x12+.com.omniview.pluginsdk.QueryMetricsRequest\x1a,.com.omniview.pluginsdk.QueryMetricsResponse\x12j\n" +
	"\rStreamMetrics\x12).com.omniview.pluginsdk.MetricStreamInput\x1a*.com.omniview.pluginsdk.MetricStreamOutput(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_metric_proto_rawDescOnce sync.Once
	file_proto_metric_proto_rawDescData []byte
)

func file_proto_metric_proto_rawDescGZIP() []byte {
	file_proto_metric_proto_rawDescOnce.Do(func() {
		file_proto_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)))
	})
	return file_proto_metric_proto_rawDescData
}

var file_proto_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_metric_proto_goTypes = []any{
	(MetricUnit)(0),                             // 0: com.omniview.pluginsdk.MetricUnit
	(MetricShape)(0),                            // 1: com.omniview.pluginsdk.MetricShape
	(MetricStreamCommand)(0),                    // 2: com.omniview.pluginsdk.MetricStreamCommand
	(*MetricProviderInfo)(nil),                  // 3: com.omniview.pluginsdk.MetricProviderInfo
	(*MetricColorRange)(nil),                    // 4: com.omniview.pluginsdk.MetricColorRange
	(*MetricDescriptor)(nil),                    // 5: com.omniview.pluginsdk.MetricDescriptor
	(*MetricHandler)(nil),                       // 6: com.omniview.pluginsdk.MetricHandler
	(*DataPoint)(nil),                           // 7: com.omniview.pluginsdk.DataPoint
	(*TimeSeries)(nil),                          // 8: com.omniview.pluginsdk.TimeSeries
	(*CurrentValue)(nil),                        // 9: com.omniview.pluginsdk.CurrentValue
	(*AggregateValue)(nil),                      // 10: com.omniview.pluginsdk.AggregateValue
	(*MetricResult)(nil),                        // 11: com.omniview.pluginsdk.MetricResult
	(*GetSupportedMetricResourcesResponse)(nil), // 12: com.omniview.pluginsdk.GetSupportedMetricResourcesResponse
	(*QueryMetricsRequest)(nil),                 // 13: com.omniview.pluginsdk.QueryMetricsRequest
	(*QueryMetricsResponse)(nil),                // 14: com.omniview.pluginsdk.QueryMetricsResponse
	(*MetricStreamInput)(nil),                   // 15: com.omniview.pluginsdk.MetricStreamInput
	(*MetricStreamOutput)(nil),                  // 16: com.omniview.pluginsdk.MetricStreamOutput
	nil,                                         // 17: com.omniview.pluginsdk.DataPoint.LabelsEntry
	nil,                                         // 18: com.omniview.pluginsdk.TimeSeries.LabelsEntry
	nil,                                         // 19: com.omniview.pluginsdk.CurrentValue.LabelsEntry
	nil,                                         // 20: com.omniview.pluginsdk.AggregateValue.LabelsEntry
	nil,                                         // 21: com.omniview.pluginsdk.QueryMetricsRequest.ParamsEntry
	(*timestamppb.Timestamp)(nil),               // 22: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),                 // 23: google.protobuf.Duration
	(*structpb.Struct)(nil),                     // 24: google.protobuf.Struct
	(*emptypb.Empty)(nil),                       // 25: google.protobuf.Empty
}
var file_proto_metric_proto_depIdxs = []int32{
	0,  // 0: com.omniview.pluginsdk.MetricDescriptor.unit:type_name -> com.omniview.pluginsdk.MetricUnit
	4,  // 1: com.omniview.pluginsdk.MetricDescriptor.color_ranges:type_name -> com.omniview.pluginsdk.MetricColorRange
	1,  // 2: com.omniview.pluginsdk.MetricDescriptor.supported_shapes:type_name -> com.omniview.pluginsdk.MetricShape
	5,  // 3: com.omniview.pluginsdk.MetricHandler.metrics:type_name -> com.omniview.pluginsdk.MetricDescriptor
	22, // 4: com.omniview.pluginsdk.DataPoint.timestamp:type_name -> google.protobuf.Timestamp
	17, // 5: com.omniview.pluginsdk.DataPoint.labels:type_name -> com.omniview.pluginsdk.DataPoint.LabelsEntry
	7,  // 6: com.omniview.pluginsdk.TimeSeries.data_points:type_name -> com.omniview.pluginsdk.DataPoint
	18, // 7: com.omniview.pluginsdk.TimeSeries.labels:type_name -> com.omniview.pluginsdk.TimeSeries.LabelsEntry
	22, // 8: com.omniview.pluginsdk.CurrentValue.timestamp:type_name -> google.protobuf.Timestamp
	19, // 9: com.omniview.pluginsdk.CurrentValue.labels:type_name -> com.omniview.pluginsdk.CurrentValue.LabelsEntry
	23, // 10: com.omniview.pluginsdk.AggregateValue.window:type_name -> google.protobuf.Duration
	20, // 11: com.omniview.pluginsdk.AggregateValue.labels:type_name -> com.omniview.pluginsdk.AggregateValue.LabelsEntry
	8,  // 12: com.omniview.pluginsdk.MetricResult.time_series:type_name -> com.omniview.pluginsdk.TimeSeries
	9,  // 13: com.omniview.pluginsdk.MetricResult.current_value:type_name -> com.omniview.pluginsdk.CurrentValue
	10, // 14: com.omniview.pluginsdk.MetricResult.aggregate_value:type_name -> com.omniview.pluginsdk.AggregateValue
	3,  // 15: com.omniview.pluginsdk.GetSupportedMetricResourcesResponse.provider:type_name -> com.omniview.pluginsdk.MetricProviderInfo
	6,  // 16: com.omniview.pluginsdk.GetSupportedMetricResourcesResponse.handlers:type_name -> com.omniview.pluginsdk.MetricHandler
	24, // 17: com.omniview.pluginsdk.QueryMetricsRequest.resource_data:type_name -> google.protobuf.Struct
	1,  // 18: com.omniview.pluginsdk.QueryMetricsRequest.shape:type_name -> com.omniview.pluginsdk.MetricShape
	22, // 19: com.omniview.pluginsdk.QueryMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 20: com.omniview.pluginsdk.QueryMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	23, // 21: com.omniview.pluginsdk.QueryMetricsRequest.step:type_name -> google.protobuf.Duration
	21, // 22: com.omniview.pluginsdk.QueryMetricsRequest.params:type_name -> com.omniview.pluginsdk.QueryMetricsRequest.ParamsEntry
	11, // 23: com.omniview.pluginsdk.QueryMetricsResponse.results:type_name -> com.omniview.pluginsdk.MetricResult
	2,  // 24: com.omniview.pluginsdk.MetricStreamInput.command:type_name -> com.omniview.pluginsdk.MetricStreamCommand
	24, // 25: com.omniview.pluginsdk.MetricStreamInput.resource_data:type_name -> google.protobuf.Struct
	23, // 26: com.omniview.pluginsdk.MetricStreamInput.interval:type_name -> google.protobuf.Duration
	11, // 27: com.omniview.pluginsdk.MetricStreamOutput.results:type_name -> com.omniview.pluginsdk.MetricResult
	22, // 28: com.omniview.pluginsdk.MetricStreamOutput.timestamp:type_name -> google.protobuf.Timestamp
	25, // 29: com.omniview.pluginsdk.MetricPlugin.GetSupportedResources:input_type -> google.protobuf.Empty
	13, // 30: com.omniview.pluginsdk.MetricPlugin.Query:input_type -> com.omniview.pluginsdk.QueryMetricsRequest
	15, // 31: com.omniview.pluginsdk.MetricPlugin.StreamMetrics:input_type -> com.omniview.pluginsdk.MetricStreamInput
	12, // 32: com.omniview.pluginsdk.MetricPlugin.GetSupportedResources:output_type -> com.omniview.pluginsdk.GetSupportedMetricResourcesResponse
	14, // 33: com.omniview.pluginsdk.MetricPlugin.Query:output_type -> com.omniview.pluginsdk.QueryMetricsResponse
	16, // 34: com.omniview.pluginsdk.MetricPlugin.StreamMetrics:output_type -> com.omniview.pluginsdk.MetricStreamOutput
	32, // [32:35] is the sub-list for method output_type
	29, // [29:32] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_metric_proto_init() }
func file_proto_metric_proto_init() {
	if File_proto_metric_proto != nil {
		return
	}
	file_proto_metric_proto_msgTypes[8].OneofWrappers = []any{
		(*MetricResult_TimeSeries)(nil),
		(*MetricResult_CurrentValue)(nil),
		(*MetricResult_AggregateValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metric_proto_rawDesc), len(file_proto_metric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metric_proto_goTypes,
		DependencyIndexes: file_proto_metric_proto_depIdxs,
		EnumInfos:         file_proto_metric_proto_enumTypes,
		MessageInfos:      file_proto_metric_proto_msgTypes,
	}.Build()
	File_proto_metric_proto = out.File
	file_proto_metric_proto_goTypes = nil
	file_proto_metric_proto_depIdxs = nil
}
