// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/resource_informer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasInformerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    string                 `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasInformerRequest) Reset() {
	*x = HasInformerRequest{}
	mi := &file_proto_resource_informer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasInformerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasInformerRequest) ProtoMessage() {}

func (x *HasInformerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasInformerRequest.ProtoReflect.Descriptor instead.
func (*HasInformerRequest) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{0}
}

func (x *HasInformerRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type StartConnectionInformerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConnectionInformerRequest) Reset() {
	*x = StartConnectionInformerRequest{}
	mi := &file_proto_resource_informer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConnectionInformerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConnectionInformerRequest) ProtoMessage() {}

func (x *StartConnectionInformerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConnectionInformerRequest.ProtoReflect.Descriptor instead.
func (*StartConnectionInformerRequest) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{1}
}

func (x *StartConnectionInformerRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StartConnectionInformerRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type StopConnectionInformerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Connection    string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopConnectionInformerRequest) Reset() {
	*x = StopConnectionInformerRequest{}
	mi := &file_proto_resource_informer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopConnectionInformerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopConnectionInformerRequest) ProtoMessage() {}

func (x *StopConnectionInformerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopConnectionInformerRequest.ProtoReflect.Descriptor instead.
func (*StopConnectionInformerRequest) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{2}
}

func (x *StopConnectionInformerRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StopConnectionInformerRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type InformerEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Key        string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Connection string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Id         string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Namespace  string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*InformerEvent_Add
	//	*InformerEvent_Update
	//	*InformerEvent_Delete
	Action        isInformerEvent_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformerEvent) Reset() {
	*x = InformerEvent{}
	mi := &file_proto_resource_informer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerEvent) ProtoMessage() {}

func (x *InformerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerEvent.ProtoReflect.Descriptor instead.
func (*InformerEvent) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{3}
}

func (x *InformerEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InformerEvent) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *InformerEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InformerEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InformerEvent) GetAction() isInformerEvent_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *InformerEvent) GetAdd() *InformerAddEvent {
	if x != nil {
		if x, ok := x.Action.(*InformerEvent_Add); ok {
			return x.Add
		}
	}
	return nil
}

func (x *InformerEvent) GetUpdate() *InformerUpdateEvent {
	if x != nil {
		if x, ok := x.Action.(*InformerEvent_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *InformerEvent) GetDelete() *InformerDeleteEvent {
	if x != nil {
		if x, ok := x.Action.(*InformerEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isInformerEvent_Action interface {
	isInformerEvent_Action()
}

type InformerEvent_Add struct {
	Add *InformerAddEvent `protobuf:"bytes,5,opt,name=add,proto3,oneof"`
}

type InformerEvent_Update struct {
	Update *InformerUpdateEvent `protobuf:"bytes,6,opt,name=update,proto3,oneof"`
}

type InformerEvent_Delete struct {
	Delete *InformerDeleteEvent `protobuf:"bytes,7,opt,name=delete,proto3,oneof"`
}

func (*InformerEvent_Add) isInformerEvent_Action() {}

func (*InformerEvent_Update) isInformerEvent_Action() {}

func (*InformerEvent_Delete) isInformerEvent_Action() {}

type InformerAddEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformerAddEvent) Reset() {
	*x = InformerAddEvent{}
	mi := &file_proto_resource_informer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformerAddEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerAddEvent) ProtoMessage() {}

func (x *InformerAddEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerAddEvent.ProtoReflect.Descriptor instead.
func (*InformerAddEvent) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{4}
}

func (x *InformerAddEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type InformerUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldData       *structpb.Struct       `protobuf:"bytes,1,opt,name=old_data,json=oldData,proto3" json:"old_data,omitempty"`
	NewData       *structpb.Struct       `protobuf:"bytes,2,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformerUpdateEvent) Reset() {
	*x = InformerUpdateEvent{}
	mi := &file_proto_resource_informer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformerUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerUpdateEvent) ProtoMessage() {}

func (x *InformerUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerUpdateEvent.ProtoReflect.Descriptor instead.
func (*InformerUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{5}
}

func (x *InformerUpdateEvent) GetOldData() *structpb.Struct {
	if x != nil {
		return x.OldData
	}
	return nil
}

func (x *InformerUpdateEvent) GetNewData() *structpb.Struct {
	if x != nil {
		return x.NewData
	}
	return nil
}

type InformerDeleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformerDeleteEvent) Reset() {
	*x = InformerDeleteEvent{}
	mi := &file_proto_resource_informer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformerDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerDeleteEvent) ProtoMessage() {}

func (x *InformerDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resource_informer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerDeleteEvent.ProtoReflect.Descriptor instead.
func (*InformerDeleteEvent) Descriptor() ([]byte, []int) {
	return file_proto_resource_informer_proto_rawDescGZIP(), []int{6}
}

func (x *InformerDeleteEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_resource_informer_proto protoreflect.FileDescriptor

const file_proto_resource_informer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/resource_informer.proto\x12\x16com.omniview.pluginsdk\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"4\n" +
	"\x12HasInformerRequest\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\"R\n" +
	"\x1eStartConnectionInformerRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\"Q\n" +
	"\x1dStopConnectionInformerRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\"\xc5\x02\n" +
	"\rInformerEvent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12<\n" +
	"\x03add\x18\x05 \x01(\v2(.com.omniview.pluginsdk.InformerAddEventH\x00R\x03add\x12E\n" +
	"\x06update\x18\x06 \x01(\v2+.com.omniview.pluginsdk.InformerUpdateEventH\x00R\x06update\x12E\n" +
	"\x06delete\x18\a \x01(\v2+.com.omniview.pluginsdk.InformerDeleteEventH\x00R\x06deleteB\b\n" +
	"\x06action\"?\n" +
	"\x10InformerAddEvent\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"}\n" +
	"\x13InformerUpdateEvent\x122\n" +
	"\bold_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\aoldData\x122\n" +
	"\bnew_data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\anewData\"B\n" +
	"\x13InformerDeleteEvent\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04dataB\tZ\a./protob\x06proto3"

var (
	file_proto_resource_informer_proto_rawDescOnce sync.Once
	file_proto_resource_informer_proto_rawDescData []byte
)

func file_proto_resource_informer_proto_rawDescGZIP() []byte {
	file_proto_resource_informer_proto_rawDescOnce.Do(func() {
		file_proto_resource_informer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resource_informer_proto_rawDesc), len(file_proto_resource_informer_proto_rawDesc)))
	})
	return file_proto_resource_informer_proto_rawDescData
}

var file_proto_resource_informer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_resource_informer_proto_goTypes = []any{
	(*HasInformerRequest)(nil),             // 0: com.omniview.pluginsdk.HasInformerRequest
	(*StartConnectionInformerRequest)(nil), // 1: com.omniview.pluginsdk.StartConnectionInformerRequest
	(*StopConnectionInformerRequest)(nil),  // 2: com.omniview.pluginsdk.StopConnectionInformerRequest
	(*InformerEvent)(nil),                  // 3: com.omniview.pluginsdk.InformerEvent
	(*InformerAddEvent)(nil),               // 4: com.omniview.pluginsdk.InformerAddEvent
	(*InformerUpdateEvent)(nil),            // 5: com.omniview.pluginsdk.InformerUpdateEvent
	(*InformerDeleteEvent)(nil),            // 6: com.omniview.pluginsdk.InformerDeleteEvent
	(*structpb.Struct)(nil),                // 7: google.protobuf.Struct
}
var file_proto_resource_informer_proto_depIdxs = []int32{
	4, // 0: com.omniview.pluginsdk.InformerEvent.add:type_name -> com.omniview.pluginsdk.InformerAddEvent
	5, // 1: com.omniview.pluginsdk.InformerEvent.update:type_name -> com.omniview.pluginsdk.InformerUpdateEvent
	6, // 2: com.omniview.pluginsdk.InformerEvent.delete:type_name -> com.omniview.pluginsdk.InformerDeleteEvent
	7, // 3: com.omniview.pluginsdk.InformerAddEvent.data:type_name -> google.protobuf.Struct
	7, // 4: com.omniview.pluginsdk.InformerUpdateEvent.old_data:type_name -> google.protobuf.Struct
	7, // 5: com.omniview.pluginsdk.InformerUpdateEvent.new_data:type_name -> google.protobuf.Struct
	7, // 6: com.omniview.pluginsdk.InformerDeleteEvent.data:type_name -> google.protobuf.Struct
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_resource_informer_proto_init() }
func file_proto_resource_informer_proto_init() {
	if File_proto_resource_informer_proto != nil {
		return
	}
	file_proto_resource_informer_proto_msgTypes[3].OneofWrappers = []any{
		(*InformerEvent_Add)(nil),
		(*InformerEvent_Update)(nil),
		(*InformerEvent_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resource_informer_proto_rawDesc), len(file_proto_resource_informer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_resource_informer_proto_goTypes,
		DependencyIndexes: file_proto_resource_informer_proto_depIdxs,
		MessageInfos:      file_proto_resource_informer_proto_msgTypes,
	}.Build()
	File_proto_resource_informer_proto = out.File
	file_proto_resource_informer_proto_goTypes = nil
	file_proto_resource_informer_proto_depIdxs = nil
}
